window.PIXELFLOW_LEVEL_26 = {
  "id": "coffee",
  "name": "coffee",
  "displayName": "Coffee",
  "fallbackFieldPattern": [
    ".......KKKKKKKKKKK.......",
    ".....KKWWWWWWWWWWWKK.....",
    ".....KEEEWWWWWWWEEEK.....",
    "....KKKKKKKKKKKKKKKKK....",
    "...KEUWWWWWWWWWWWWWUEK...",
    "...KEUUWWWWWWWWWWUUUEK...",
    "...KEEEUUUUUUUUUUEEEEK...",
    "...KKKKKKKKKKKKKKKKKKK...",
    "....KUUUUUUUUUUUUUUUK....",
    "....KUWWWWKKKKKWWWWUK....",
    "....KUWWWKCCWCCKWWWUK....",
    "....KUWWKCCWWWCCKWWUK....",
    "....KUWKCWCCWCCWCKWUK....",
    "....KUWKWCWWWWWCWKWUK....",
    "....KUWKWCCWCWCCWKWUK....",
    "....KUWKCWCCWCCWCKWUK....",
    ".....KUKCWCWWWCWCKUK.....",
    ".....KUWKWCWWWCWKWUK.....",
    ".....KUWWKCWWWCKWWUK.....",
    "......KUWWKKKKKWWUK......",
    "......KUWWWWWWWWWUK......",
    "......KUEWWWWWWWEUK......",
    "......KKEEEEEEEEEKK......",
    ".......KKKKKKKKKKK.......",
    ".......KKKKKKKKKKK......."
  ],
  "referenceGrid": {
    "x": 262,
    "y": 420,
    "step": 20,
    "cellSize": 18
  },
  "layout": {
    "fieldX": 262,
    "fieldY": 420,
    "fieldStep": 20,
    "cellSize": 18,
    "fieldCols": 25,
    "fieldRows": 25,
    "track": {
      "x": 106,
      "y": 189,
      "w": 808,
      "h": 856,
      "r": 50
    },
    "spawnPoint": {
      "x": 152,
      "y": 979
    },
    "cards": [
      {
        "lane": 0,
        "row": 0,
        "x": 312,
        "y": 1230,
        "w": 160,
        "h": 200,
        "color": "green",
        "styleKey": "mint",
        "label": 1,
        "ammo": 40
      },
      {
        "lane": 1,
        "row": 0,
        "x": 552,
        "y": 1230,
        "w": 160,
        "h": 200,
        "color": "black",
        "styleKey": "coral",
        "label": 2,
        "ammo": 40
      },
      {
        "lane": 0,
        "row": 1,
        "x": 312,
        "y": 1432,
        "w": 160,
        "h": 200,
        "color": "green",
        "styleKey": "sky",
        "label": 3,
        "ammo": 40
      },
      {
        "lane": 1,
        "row": 1,
        "x": 552,
        "y": 1432,
        "w": 160,
        "h": 200,
        "color": "black",
        "styleKey": "gold",
        "label": 4,
        "ammo": 40
      }
    ],
    "slots": [
      {
        "x": 98,
        "y": 1130,
        "w": 194,
        "h": 126
      },
      {
        "x": 311,
        "y": 1130,
        "w": 194,
        "h": 126
      },
      {
        "x": 520,
        "y": 1130,
        "w": 194,
        "h": 126
      },
      {
        "x": 729,
        "y": 1130,
        "w": 194,
        "h": 126
      }
    ],
    "wagonSprite": {
      "x": 44,
      "y": 840,
      "w": 148,
      "h": 116,
      "anchorX": 52,
      "anchorY": 96,
      "seatOffsetX": 0,
      "seatOffsetY": -52
    },
    "wagonMask": {
      "x": 0,
      "y": 820,
      "w": 260,
      "h": 200
    },
    "boardMask": {
      "x": 0,
      "y": 0,
      "w": 1024,
      "h": 1600,
      "r": 0
    }
  },
  "queueCardCount": 6,
  "pixelArt": {
    "id": "level-26-art",
    "name": "starbucks_25х25.png",
    "sourceFileName": "starbucks_25х25.png",
    "birdCount": 6,
    "artScale": 1,
    "offsetY": -37,
    "grid": {
      "cols": 25,
      "rows": 25
    },
    "pattern": [
      ".......KKKKKKKKKKK.......",
      ".....KKWWWWWWWWWWWKK.....",
      ".....KEEEWWWWWWWEEEK.....",
      "....KKKKKKKKKKKKKKKKK....",
      "...KEUWWWWWWWWWWWWWUEK...",
      "...KEUUWWWWWWWWWWUUUEK...",
      "...KEEEUUUUUUUUUUEEEEK...",
      "...KKKKKKKKKKKKKKKKKKK...",
      "....KUUUUUUUUUUUUUUUK....",
      "....KUWWWWKKKKKWWWWUK....",
      "....KUWWWKCCWCCKWWWUK....",
      "....KUWWKCCWWWCCKWWUK....",
      "....KUWKCWCCWCCWCKWUK....",
      "....KUWKWCWWWWWCWKWUK....",
      "....KUWKWCCWCWCCWKWUK....",
      "....KUWKCWCCWCCWCKWUK....",
      ".....KUKCWCWWWCWCKUK.....",
      ".....KUWKWCWWWCWKWUK.....",
      ".....KUWWKCWWWCKWWUK.....",
      "......KUWWKKKKKWWUK......",
      "......KUWWWWWWWWWUK......",
      "......KUEWWWWWWWEUK......",
      "......KKEEEEEEEEEKK......",
      ".......KKKKKKKKKKK.......",
      ".......KKKKKKKKKKK......."
    ],
    "colorMatrix": [
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        "black",
        "black",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "black",
        "black",
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        "black",
        "peach",
        "peach",
        "peach",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "peach",
        "peach",
        "peach",
        "black",
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        "black",
        "peach",
        "light_gray",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "light_gray",
        "peach",
        "black",
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        "black",
        "peach",
        "light_gray",
        "light_gray",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "light_gray",
        "light_gray",
        "light_gray",
        "peach",
        "black",
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        "black",
        "peach",
        "peach",
        "peach",
        "light_gray",
        "light_gray",
        "light_gray",
        "light_gray",
        "light_gray",
        "light_gray",
        "light_gray",
        "light_gray",
        "light_gray",
        "light_gray",
        "peach",
        "peach",
        "peach",
        "peach",
        "black",
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        "black",
        "light_gray",
        "light_gray",
        "light_gray",
        "light_gray",
        "light_gray",
        "light_gray",
        "light_gray",
        "light_gray",
        "light_gray",
        "light_gray",
        "light_gray",
        "light_gray",
        "light_gray",
        "light_gray",
        "light_gray",
        "black",
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        "black",
        "light_gray",
        "white",
        "white",
        "white",
        "white",
        "black",
        "black",
        "black",
        "black",
        "black",
        "white",
        "white",
        "white",
        "white",
        "light_gray",
        "black",
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        "black",
        "light_gray",
        "white",
        "white",
        "white",
        "black",
        "blue",
        "blue",
        "white",
        "blue",
        "blue",
        "black",
        "white",
        "white",
        "white",
        "light_gray",
        "black",
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        "black",
        "light_gray",
        "white",
        "white",
        "black",
        "blue",
        "blue",
        "white",
        "white",
        "white",
        "blue",
        "blue",
        "black",
        "white",
        "white",
        "light_gray",
        "black",
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        "black",
        "light_gray",
        "white",
        "black",
        "blue",
        "white",
        "blue",
        "blue",
        "white",
        "blue",
        "blue",
        "white",
        "blue",
        "black",
        "white",
        "light_gray",
        "black",
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        "black",
        "light_gray",
        "white",
        "black",
        "white",
        "blue",
        "white",
        "white",
        "white",
        "white",
        "white",
        "blue",
        "white",
        "black",
        "white",
        "light_gray",
        "black",
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        "black",
        "light_gray",
        "white",
        "black",
        "white",
        "blue",
        "blue",
        "white",
        "blue",
        "white",
        "blue",
        "blue",
        "white",
        "black",
        "white",
        "light_gray",
        "black",
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        "black",
        "light_gray",
        "white",
        "black",
        "blue",
        "white",
        "blue",
        "blue",
        "white",
        "blue",
        "blue",
        "white",
        "blue",
        "black",
        "white",
        "light_gray",
        "black",
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        "black",
        "light_gray",
        "black",
        "blue",
        "white",
        "blue",
        "white",
        "white",
        "white",
        "blue",
        "white",
        "blue",
        "black",
        "light_gray",
        "black",
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        "black",
        "light_gray",
        "white",
        "black",
        "white",
        "blue",
        "white",
        "white",
        "white",
        "blue",
        "white",
        "black",
        "white",
        "light_gray",
        "black",
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        "black",
        "light_gray",
        "white",
        "white",
        "black",
        "blue",
        "white",
        "white",
        "white",
        "blue",
        "black",
        "white",
        "white",
        "light_gray",
        "black",
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        "black",
        "light_gray",
        "white",
        "white",
        "black",
        "black",
        "black",
        "black",
        "black",
        "white",
        "white",
        "light_gray",
        "black",
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        "black",
        "light_gray",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "light_gray",
        "black",
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        "black",
        "light_gray",
        "peach",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "peach",
        "light_gray",
        "black",
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        "black",
        "black",
        "peach",
        "peach",
        "peach",
        "peach",
        "peach",
        "peach",
        "peach",
        "peach",
        "peach",
        "black",
        "black",
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    ]
  },
  "levelNumber": 26,
  "debugOnly": false
};
