window.PIXELFLOW_LEVEL_9 = {
  "id": "9",
  "name": "Level 9",
  "fallbackFieldPattern": [
    ".....KKKKKKK.....",
    "...KKCCCCCCCKK...",
    "..KCCKKKKKKKCCK..",
    ".KCCKCCCCCCCKCCK.",
    "KCCCCCKKKKKCCCCCK",
    "KCCCCCCCCCCCCCCCK",
    "KCCCCKKCCCKKCCCCK",
    "KCCCKYYKKKYYKCCCK",
    ".KCKYYNYKYNYYKCK.",
    "..KKYYNYKYNYYKK..",
    "...KYYYYKYYYYK...",
    "....KYYKCKYYK....",
    "...KCKKCCCKKCK...",
    "..KCCCKCCCKCCCK..",
    "..KCKKCCCCCKKCK..",
    "..KCCKCCCCCKCCK..",
    "...KKKCCCCCKKK...",
    "......KCCCK......",
    ".......KKK......."
  ],
  "referenceGrid": {
    "x": 283,
    "y": 134,
    "step": 27,
    "cellSize": 25
  },
  "layout": {
    "fieldX": 283,
    "fieldY": 134,
    "fieldStep": 27,
    "cellSize": 25,
    "fieldCols": 17,
    "fieldRows": 19,
    "track": {
      "x": 106,
      "y": 189,
      "w": 808,
      "h": 856,
      "r": 50
    },
    "spawnPoint": {
      "x": 152,
      "y": 979
    },
    "cards": [
      {
        "lane": 0,
        "row": 0,
        "x": 312,
        "y": 1230,
        "w": 160,
        "h": 200,
        "color": "green",
        "styleKey": "mint",
        "label": 1,
        "ammo": 40
      },
      {
        "lane": 1,
        "row": 0,
        "x": 552,
        "y": 1230,
        "w": 160,
        "h": 200,
        "color": "black",
        "styleKey": "coral",
        "label": 2,
        "ammo": 40
      },
      {
        "lane": 0,
        "row": 1,
        "x": 312,
        "y": 1432,
        "w": 160,
        "h": 200,
        "color": "green",
        "styleKey": "sky",
        "label": 3,
        "ammo": 40
      },
      {
        "lane": 1,
        "row": 1,
        "x": 552,
        "y": 1432,
        "w": 160,
        "h": 200,
        "color": "black",
        "styleKey": "gold",
        "label": 4,
        "ammo": 40
      }
    ],
    "slots": [
      {
        "x": 98,
        "y": 1130,
        "w": 194,
        "h": 126
      },
      {
        "x": 311,
        "y": 1130,
        "w": 194,
        "h": 126
      },
      {
        "x": 520,
        "y": 1130,
        "w": 194,
        "h": 126
      },
      {
        "x": 729,
        "y": 1130,
        "w": 194,
        "h": 126
      }
    ],
    "wagonSprite": {
      "x": 44,
      "y": 840,
      "w": 148,
      "h": 116,
      "anchorX": 52,
      "anchorY": 96,
      "seatOffsetX": 0,
      "seatOffsetY": -52
    },
    "wagonMask": {
      "x": 0,
      "y": 820,
      "w": 260,
      "h": 200
    },
    "boardMask": {
      "x": 0,
      "y": 0,
      "w": 1024,
      "h": 1600,
      "r": 0
    }
  },
  "queueCardCount": 7,
  "pixelArt": {
    "id": "level-9-art",
    "name": "36b8c917-7e98-4de6-8d25-aac290041817.png",
    "sourceFileName": "36b8c917-7e98-4de6-8d25-aac290041817.png",
    "artScale": 1.05,
    "offsetY": -37,
    "grid": {
      "cols": 17,
      "rows": 19
    },
    "pattern": [
      ".....KKKKKKK.....",
      "...KKCCCCCCCKK...",
      "..KCCKKKKKKKCCK..",
      ".KCCKCCCCCCCKCCK.",
      "KCCCCCKKKKKCCCCCK",
      "KCCCCCCCCCCCCCCCK",
      "KCCCCKKCCCKKCCCCK",
      "KCCCKYYKKKYYKCCCK",
      ".KCKYYNYKYNYYKCK.",
      "..KKYYNYKYNYYKK..",
      "...KYYYYKYYYYK...",
      "....KYYKCKYYK....",
      "...KCKKCCCKKCK...",
      "..KCCCKCCCKCCCK..",
      "..KCKKCCCCCKKCK..",
      "..KCCKCCCCCKCCK..",
      "...KKKCCCCCKKK...",
      "......KCCCK......",
      ".......KKK......."
    ],
    "colorMatrix": [
      [
        null,
        null,
        null,
        null,
        null,
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        "black",
        "black",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "black",
        "black",
        null,
        null,
        null
      ],
      [
        null,
        null,
        "black",
        "blue",
        "blue",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "blue",
        "blue",
        "black",
        null,
        null
      ],
      [
        null,
        "black",
        "blue",
        "blue",
        "black",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "black",
        "blue",
        "blue",
        "black",
        null
      ],
      [
        "black",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "black",
        "black",
        "black",
        "black",
        "black",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "black"
      ],
      [
        "black",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "black"
      ],
      [
        "black",
        "blue",
        "blue",
        "blue",
        "blue",
        "black",
        "black",
        "blue",
        "blue",
        "blue",
        "black",
        "black",
        "blue",
        "blue",
        "blue",
        "blue",
        "black"
      ],
      [
        "black",
        "blue",
        "blue",
        "blue",
        "black",
        "yellow",
        "yellow",
        "black",
        "black",
        "black",
        "yellow",
        "yellow",
        "black",
        "blue",
        "blue",
        "blue",
        "black"
      ],
      [
        null,
        "black",
        "blue",
        "black",
        "yellow",
        "yellow",
        "brown",
        "yellow",
        "black",
        "yellow",
        "brown",
        "yellow",
        "yellow",
        "black",
        "blue",
        "black",
        null
      ],
      [
        null,
        null,
        "black",
        "black",
        "yellow",
        "yellow",
        "brown",
        "yellow",
        "black",
        "yellow",
        "brown",
        "yellow",
        "yellow",
        "black",
        "black",
        null,
        null
      ],
      [
        null,
        null,
        null,
        "black",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "black",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "black",
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        "black",
        "yellow",
        "yellow",
        "black",
        "blue",
        "black",
        "yellow",
        "yellow",
        "black",
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        "black",
        "blue",
        "black",
        "black",
        "blue",
        "blue",
        "blue",
        "black",
        "black",
        "blue",
        "black",
        null,
        null,
        null
      ],
      [
        null,
        null,
        "black",
        "blue",
        "blue",
        "blue",
        "black",
        "blue",
        "blue",
        "blue",
        "black",
        "blue",
        "blue",
        "blue",
        "black",
        null,
        null
      ],
      [
        null,
        null,
        "black",
        "blue",
        "black",
        "black",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "black",
        "black",
        "blue",
        "black",
        null,
        null
      ],
      [
        null,
        null,
        "black",
        "blue",
        "blue",
        "black",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "black",
        "blue",
        "blue",
        "black",
        null,
        null
      ],
      [
        null,
        null,
        null,
        "black",
        "black",
        "black",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "black",
        "black",
        "black",
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        "black",
        "blue",
        "blue",
        "blue",
        "black",
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "black",
        "black",
        "black",
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    ],
    "birdCount": 7
  }
};
