window.PIXELFLOW_LEVEL_5 = {
  "id": "5",
  "name": "Level 5",
  "fallbackFieldPattern": [
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWGGGGWWWWWW",
    "WWWWWWWWWWWWWWWWGGGGGGGWWWWW",
    "WWWWWWWWWWWWWWGGGGYYYYGGWWWW",
    "WWWWWWWWWWWWWGGGYYYYYYGGGWWW",
    "WWWWWWWWWWWWGGYYYYYYYYYGGWWW",
    "WWWWWWWWWWWGGYYYYYYYYYYGGWWW",
    "WWWWWWWWWWGGYYYYYYYYYYGGGWWW",
    "WWWWWWWWGGYYYYYYYYYYYYGGGWWW",
    "WWWWWWWGGYYYKNNNNNYYYYGGGWWW",
    "WWWWWWGGYYYKOOOONNNYYYGGGWWW",
    "WWWWWGGYYYKOOOOKKNNYYYGGGWWW",
    "WWWWGGYYYKNOOOONNNKYYYGGGWWW",
    "WWWWGGYYNNKOOOONNNNYYYGGGWWW",
    "WWWGGYYYKNNNKNNNNNNYYYGGGWWW",
    "WWWGGYYYNNNNNKNNNNKYYYGGGWWW",
    "WWWGGYYYKNNNNKNNNKYYYGGGGWWW",
    "WWWGGYYYYKNKKKKNKYYYYGGGGWWW",
    "WWWGGYYYYYKKKKKKYYYYGGGGGWWW",
    "WWWGGGYYYYYYYYYYYYYGGGGGWWWW",
    "WWWGGGGYYYYYYYYYYGGGGGGGWWWW",
    "WWWWGGGGGYYYYYYYGGGGGGGWWWWW",
    "WWWWWGGGGGGGGGGGGGGGGGGWWWWW",
    "WWWWWWGGGGGGGGGGGGGGGGWWWWWW",
    "WWWWWWWGGGGGGGGGGGGGWWWWWWWW",
    "WWWWWWWWWGGGGGGGGGGWWWWWWWWW",
    "WWWWWWWWWWWGGGGLWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWW"
  ],
  "referenceGrid": {
    "x": 274,
    "y": 226,
    "step": 17,
    "cellSize": 15
  },
  "layout": {
    "fieldX": 274,
    "fieldY": 226,
    "fieldStep": 17,
    "cellSize": 15,
    "fieldCols": 28,
    "fieldRows": 28,
    "track": {
      "x": 106,
      "y": 189,
      "w": 808,
      "h": 856,
      "r": 50
    },
    "spawnPoint": {
      "x": 152,
      "y": 979
    },
    "cards": [
      {
        "lane": 0,
        "row": 0,
        "x": 312,
        "y": 1230,
        "w": 160,
        "h": 200,
        "color": "green",
        "styleKey": "mint",
        "label": 1,
        "ammo": 40
      },
      {
        "lane": 1,
        "row": 0,
        "x": 552,
        "y": 1230,
        "w": 160,
        "h": 200,
        "color": "black",
        "styleKey": "coral",
        "label": 2,
        "ammo": 40
      },
      {
        "lane": 0,
        "row": 1,
        "x": 312,
        "y": 1432,
        "w": 160,
        "h": 200,
        "color": "green",
        "styleKey": "sky",
        "label": 3,
        "ammo": 40
      },
      {
        "lane": 1,
        "row": 1,
        "x": 552,
        "y": 1432,
        "w": 160,
        "h": 200,
        "color": "black",
        "styleKey": "gold",
        "label": 4,
        "ammo": 40
      }
    ],
    "slots": [
      {
        "x": 98,
        "y": 1130,
        "w": 194,
        "h": 126
      },
      {
        "x": 311,
        "y": 1130,
        "w": 194,
        "h": 126
      },
      {
        "x": 520,
        "y": 1130,
        "w": 194,
        "h": 126
      },
      {
        "x": 729,
        "y": 1130,
        "w": 194,
        "h": 126
      }
    ],
    "wagonSprite": {
      "x": 44,
      "y": 840,
      "w": 148,
      "h": 116,
      "anchorX": 52,
      "anchorY": 96,
      "seatOffsetX": 0,
      "seatOffsetY": -52
    },
    "wagonMask": {
      "x": 0,
      "y": 820,
      "w": 260,
      "h": 200
    },
    "boardMask": {
      "x": 0,
      "y": 0,
      "w": 1024,
      "h": 1600,
      "r": 0
    }
  },
  "queueCardCount": 7,
  "pixelArt": {
    "id": "level-5-art",
    "name": "avocado.png",
    "sourceFileName": "avocado.png",
    "artScale": 1,
    "offsetY": -37,
    "grid": {
      "cols": 28,
      "rows": 28
    },
    "pattern": [
      "WWWWWWWWWWWWWWWWWWWWWWWWWWWW",
      "WWWWWWWWWWWWWWWWWWGGGGWWWWWW",
      "WWWWWWWWWWWWWWWWGGGGGGGWWWWW",
      "WWWWWWWWWWWWWWGGGGYYYYGGWWWW",
      "WWWWWWWWWWWWWGGGYYYYYYGGGWWW",
      "WWWWWWWWWWWWGGYYYYYYYYYGGWWW",
      "WWWWWWWWWWWGGYYYYYYYYYYGGWWW",
      "WWWWWWWWWWGGYYYYYYYYYYGGGWWW",
      "WWWWWWWWGGYYYYYYYYYYYYGGGWWW",
      "WWWWWWWGGYYYKNNNNNYYYYGGGWWW",
      "WWWWWWGGYYYKOOOONNNYYYGGGWWW",
      "WWWWWGGYYYKOOOOKKNNYYYGGGWWW",
      "WWWWGGYYYKNOOOONNNKYYYGGGWWW",
      "WWWWGGYYNNKOOOONNNNYYYGGGWWW",
      "WWWGGYYYKNNNKNNNNNNYYYGGGWWW",
      "WWWGGYYYNNNNNKNNNNKYYYGGGWWW",
      "WWWGGYYYKNNNNKNNNKYYYGGGGWWW",
      "WWWGGYYYYKNKKKKNKYYYYGGGGWWW",
      "WWWGGYYYYYKKKKKKYYYYGGGGGWWW",
      "WWWGGGYYYYYYYYYYYYYGGGGGWWWW",
      "WWWGGGGYYYYYYYYYYGGGGGGGWWWW",
      "WWWWGGGGGYYYYYYYGGGGGGGWWWWW",
      "WWWWWGGGGGGGGGGGGGGGGGGWWWWW",
      "WWWWWWGGGGGGGGGGGGGGGGWWWWWW",
      "WWWWWWWGGGGGGGGGGGGGWWWWWWWW",
      "WWWWWWWWWGGGGGGGGGGWWWWWWWWW",
      "WWWWWWWWWWWGGGGLWWWWWWWWWWWW",
      "WWWWWWWWWWWWWWWWWWWWWWWWWWWW"
    ],
    "colorMatrix": [
      [
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white"
      ],
      [
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "green",
        "green",
        "green",
        "green",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white"
      ],
      [
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "white",
        "white",
        "white",
        "white",
        "white"
      ],
      [
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "green",
        "green",
        "green",
        "green",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "green",
        "green",
        "white",
        "white",
        "white",
        "white"
      ],
      [
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "green",
        "green",
        "green",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "green",
        "green",
        "green",
        "white",
        "white",
        "white"
      ],
      [
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "green",
        "green",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "green",
        "green",
        "white",
        "white",
        "white"
      ],
      [
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "green",
        "green",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "green",
        "green",
        "white",
        "white",
        "white"
      ],
      [
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "green",
        "green",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "green",
        "green",
        "green",
        "white",
        "white",
        "white"
      ],
      [
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "green",
        "green",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "green",
        "green",
        "green",
        "white",
        "white",
        "white"
      ],
      [
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "green",
        "green",
        "yellow",
        "yellow",
        "yellow",
        "black",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "green",
        "green",
        "green",
        "white",
        "white",
        "white"
      ],
      [
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "green",
        "green",
        "yellow",
        "yellow",
        "yellow",
        "black",
        "orange",
        "orange",
        "orange",
        "orange",
        "brown",
        "brown",
        "brown",
        "yellow",
        "yellow",
        "yellow",
        "green",
        "green",
        "green",
        "white",
        "white",
        "white"
      ],
      [
        "white",
        "white",
        "white",
        "white",
        "white",
        "green",
        "green",
        "yellow",
        "yellow",
        "yellow",
        "black",
        "orange",
        "orange",
        "orange",
        "orange",
        "black",
        "black",
        "brown",
        "brown",
        "yellow",
        "yellow",
        "yellow",
        "green",
        "green",
        "green",
        "white",
        "white",
        "white"
      ],
      [
        "white",
        "white",
        "white",
        "white",
        "green",
        "green",
        "yellow",
        "yellow",
        "yellow",
        "black",
        "brown",
        "orange",
        "orange",
        "orange",
        "orange",
        "brown",
        "brown",
        "brown",
        "black",
        "yellow",
        "yellow",
        "yellow",
        "green",
        "green",
        "green",
        "white",
        "white",
        "white"
      ],
      [
        "white",
        "white",
        "white",
        "white",
        "green",
        "green",
        "yellow",
        "yellow",
        "brown",
        "brown",
        "black",
        "orange",
        "orange",
        "orange",
        "orange",
        "brown",
        "brown",
        "brown",
        "brown",
        "yellow",
        "yellow",
        "yellow",
        "green",
        "green",
        "green",
        "white",
        "white",
        "white"
      ],
      [
        "white",
        "white",
        "white",
        "green",
        "green",
        "yellow",
        "yellow",
        "yellow",
        "black",
        "brown",
        "brown",
        "brown",
        "black",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "yellow",
        "yellow",
        "yellow",
        "green",
        "green",
        "green",
        "white",
        "white",
        "white"
      ],
      [
        "white",
        "white",
        "white",
        "green",
        "green",
        "yellow",
        "yellow",
        "yellow",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "black",
        "brown",
        "brown",
        "brown",
        "brown",
        "black",
        "yellow",
        "yellow",
        "yellow",
        "green",
        "green",
        "green",
        "white",
        "white",
        "white"
      ],
      [
        "white",
        "white",
        "white",
        "green",
        "green",
        "yellow",
        "yellow",
        "yellow",
        "black",
        "brown",
        "brown",
        "brown",
        "brown",
        "black",
        "brown",
        "brown",
        "brown",
        "black",
        "yellow",
        "yellow",
        "yellow",
        "green",
        "green",
        "green",
        "green",
        "white",
        "white",
        "white"
      ],
      [
        "white",
        "white",
        "white",
        "green",
        "green",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "black",
        "brown",
        "black",
        "black",
        "black",
        "black",
        "brown",
        "black",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "green",
        "green",
        "green",
        "green",
        "white",
        "white",
        "white"
      ],
      [
        "white",
        "white",
        "white",
        "green",
        "green",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "green",
        "green",
        "green",
        "green",
        "green",
        "white",
        "white",
        "white"
      ],
      [
        "white",
        "white",
        "white",
        "green",
        "green",
        "green",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "green",
        "green",
        "green",
        "green",
        "green",
        "white",
        "white",
        "white",
        "white"
      ],
      [
        "white",
        "white",
        "white",
        "green",
        "green",
        "green",
        "green",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "white",
        "white",
        "white",
        "white"
      ],
      [
        "white",
        "white",
        "white",
        "white",
        "green",
        "green",
        "green",
        "green",
        "green",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "white",
        "white",
        "white",
        "white",
        "white"
      ],
      [
        "white",
        "white",
        "white",
        "white",
        "white",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "white",
        "white",
        "white",
        "white",
        "white"
      ],
      [
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white"
      ],
      [
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white"
      ],
      [
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white"
      ],
      [
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "green",
        "green",
        "green",
        "green",
        "light_green",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white"
      ],
      [
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white"
      ]
    ]
  }
};
