window.PIXELFLOW_LEVEL_1 = {
  "id": "1",
  "name": "Level 1",
  "fallbackFieldPattern": [
    "WWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWKKKWWWWWWWWWWW",
    "WWWWWWWWWWKLLLKWWWWWWWWWW",
    "WWWWWWWWKKKKKKLKWWWWWWWWW",
    "WWWWWWKKGGGGGGKKWKKWWWWWW",
    "WWWWWKGGGGGGGGGGKLLKWWWWW",
    "WWWWKGGGGGGGGGGGGKLKWWWWW",
    "WWWWKGGGGGGGGGGGGGKWWWWWW",
    "WWWKGGGGGGGGGGGGGGKWKWWWW",
    "WWWKGGGGGGGGGGGGGGGKLKWWW",
    "WWWKGKKGGGGGGKKGGGGKLKWWW",
    "WWWKSKKGGGGGGKKSGGGKKWWWW",
    "WWWKSSGGKGGKGGSSGGGKWWWWW",
    "WWWKGGGGGKKGGGGGGGKLKWWWW",
    "WWWKGGGGGGGGGGGGGGKLKWWWW",
    "WWWWKGGGGGGGGGGGGKLLKWWWW",
    "WWWWWKKGGGGGGGGKKWKKWWWWW",
    "WWWWWWWKKKKKKKKKLKWWWWWWW",
    "WWWWWWKGLLLGGGGGKKWWWWWWW",
    "WWWWWWKLLLLLGGGGKLKWWWWWW",
    "WWWWKKKLLLLKKKGGGKLKWWWWW",
    "WWWWKGGKLLKGGGKGGGKKKWWWW",
    "WWWWKGGKLLKGGGGGKGGGKWWWW",
    "WWWWWKKKKKKKKKKKKKKKWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWW"
  ],
  "referenceGrid": {
    "x": 212,
    "y": 407,
    "step": 24,
    "cellSize": 22
  },
  "layout": {
    "fieldX": 212,
    "fieldY": 407,
    "fieldStep": 24,
    "cellSize": 22,
    "fieldCols": 25,
    "fieldRows": 25,
    "track": {
      "x": 106,
      "y": 189,
      "w": 808,
      "h": 856,
      "r": 50
    },
    "spawnPoint": {
      "x": 152,
      "y": 979
    },
    "cards": [
      {
        "lane": 0,
        "row": 0,
        "x": 312,
        "y": 1230,
        "w": 160,
        "h": 200,
        "color": "green",
        "styleKey": "mint",
        "label": 1,
        "ammo": 40
      },
      {
        "lane": 1,
        "row": 0,
        "x": 552,
        "y": 1230,
        "w": 160,
        "h": 200,
        "color": "black",
        "styleKey": "coral",
        "label": 2,
        "ammo": 40
      },
      {
        "lane": 0,
        "row": 1,
        "x": 312,
        "y": 1432,
        "w": 160,
        "h": 200,
        "color": "green",
        "styleKey": "sky",
        "label": 3,
        "ammo": 40
      },
      {
        "lane": 1,
        "row": 1,
        "x": 552,
        "y": 1432,
        "w": 160,
        "h": 200,
        "color": "black",
        "styleKey": "gold",
        "label": 4,
        "ammo": 40
      }
    ],
    "slots": [
      {
        "x": 98,
        "y": 1130,
        "w": 194,
        "h": 126
      },
      {
        "x": 311,
        "y": 1130,
        "w": 194,
        "h": 126
      },
      {
        "x": 520,
        "y": 1130,
        "w": 194,
        "h": 126
      },
      {
        "x": 729,
        "y": 1130,
        "w": 194,
        "h": 126
      }
    ],
    "wagonSprite": {
      "x": 44,
      "y": 840,
      "w": 148,
      "h": 116,
      "anchorX": 52,
      "anchorY": 96,
      "seatOffsetX": 0,
      "seatOffsetY": -52
    },
    "wagonMask": {
      "x": 0,
      "y": 820,
      "w": 260,
      "h": 200
    },
    "boardMask": {
      "x": 0,
      "y": 0,
      "w": 1024,
      "h": 1600,
      "r": 0
    }
  },
  "queueCardCount": 7,
  "pixelArt": {
    "id": "level-1-art",
    "name": "dino.png",
    "sourceFileName": "dino.png",
    "artScale": 0.9,
    "offsetY": -37,
    "grid": {
      "cols": 25,
      "rows": 25
    },
    "pattern": [
      "WWWWWWWWWWWWWWWWWWWWWWWWW",
      "WWWWWWWWWWWKKKWWWWWWWWWWW",
      "WWWWWWWWWWKLLLKWWWWWWWWWW",
      "WWWWWWWWKKKKKKLKWWWWWWWWW",
      "WWWWWWKKGGGGGGKKWKKWWWWWW",
      "WWWWWKGGGGGGGGGGKLLKWWWWW",
      "WWWWKGGGGGGGGGGGGKLKWWWWW",
      "WWWWKGGGGGGGGGGGGGKWWWWWW",
      "WWWKGGGGGGGGGGGGGGKWKWWWW",
      "WWWKGGGGGGGGGGGGGGGKLKWWW",
      "WWWKGKKGGGGGGKKGGGGKLKWWW",
      "WWWKSKKGGGGGGKKSGGGKKWWWW",
      "WWWKSSGGKGGKGGSSGGGKWWWWW",
      "WWWKGGGGGKKGGGGGGGKLKWWWW",
      "WWWKGGGGGGGGGGGGGGKLKWWWW",
      "WWWWKGGGGGGGGGGGGKLLKWWWW",
      "WWWWWKKGGGGGGGGKKWKKWWWWW",
      "WWWWWWWKKKKKKKKKLKWWWWWWW",
      "WWWWWWKGLLLGGGGGKKWWWWWWW",
      "WWWWWWKLLLLLGGGGKLKWWWWWW",
      "WWWWKKKLLLLKKKGGGKLKWWWWW",
      "WWWWKGGKLLKGGGKGGGKKKWWWW",
      "WWWWKGGKLLKGGGGGKGGGKWWWW",
      "WWWWWKKKKKKKKKKKKKKKWWWWW",
      "WWWWWWWWWWWWWWWWWWWWWWWWW"
    ],
    "colorMatrix": [
      [
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white"
      ],
      [
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "black",
        "black",
        "black",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white"
      ],
      [
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "black",
        "light_green",
        "light_green",
        "light_green",
        "black",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white"
      ],
      [
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "light_green",
        "black",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white"
      ],
      [
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "black",
        "black",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "black",
        "black",
        "white",
        "black",
        "black",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white"
      ],
      [
        "white",
        "white",
        "white",
        "white",
        "white",
        "black",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "black",
        "light_green",
        "light_green",
        "black",
        "white",
        "white",
        "white",
        "white",
        "white"
      ],
      [
        "white",
        "white",
        "white",
        "white",
        "black",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "black",
        "light_green",
        "black",
        "white",
        "white",
        "white",
        "white",
        "white"
      ],
      [
        "white",
        "white",
        "white",
        "white",
        "black",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "black",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white"
      ],
      [
        "white",
        "white",
        "white",
        "black",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "black",
        "white",
        "black",
        "white",
        "white",
        "white",
        "white"
      ],
      [
        "white",
        "white",
        "white",
        "black",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "black",
        "light_green",
        "black",
        "white",
        "white",
        "white"
      ],
      [
        "white",
        "white",
        "white",
        "black",
        "green",
        "black",
        "black",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "black",
        "black",
        "green",
        "green",
        "green",
        "green",
        "black",
        "light_green",
        "black",
        "white",
        "white",
        "white"
      ],
      [
        "white",
        "white",
        "white",
        "black",
        "rose",
        "black",
        "black",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "black",
        "black",
        "rose",
        "green",
        "green",
        "green",
        "black",
        "black",
        "white",
        "white",
        "white",
        "white"
      ],
      [
        "white",
        "white",
        "white",
        "black",
        "rose",
        "rose",
        "green",
        "green",
        "black",
        "green",
        "green",
        "black",
        "green",
        "green",
        "rose",
        "rose",
        "green",
        "green",
        "green",
        "black",
        "white",
        "white",
        "white",
        "white",
        "white"
      ],
      [
        "white",
        "white",
        "white",
        "black",
        "green",
        "green",
        "green",
        "green",
        "green",
        "black",
        "black",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "black",
        "light_green",
        "black",
        "white",
        "white",
        "white",
        "white"
      ],
      [
        "white",
        "white",
        "white",
        "black",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "black",
        "light_green",
        "black",
        "white",
        "white",
        "white",
        "white"
      ],
      [
        "white",
        "white",
        "white",
        "white",
        "black",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "black",
        "light_green",
        "light_green",
        "black",
        "white",
        "white",
        "white",
        "white"
      ],
      [
        "white",
        "white",
        "white",
        "white",
        "white",
        "black",
        "black",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "black",
        "black",
        "white",
        "black",
        "black",
        "white",
        "white",
        "white",
        "white",
        "white"
      ],
      [
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "light_green",
        "black",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white"
      ],
      [
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "black",
        "green",
        "light_green",
        "light_green",
        "light_green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "black",
        "black",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white"
      ],
      [
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "black",
        "light_green",
        "light_green",
        "light_green",
        "light_green",
        "light_green",
        "green",
        "green",
        "green",
        "green",
        "black",
        "light_green",
        "black",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white"
      ],
      [
        "white",
        "white",
        "white",
        "white",
        "black",
        "black",
        "black",
        "light_green",
        "light_green",
        "light_green",
        "light_green",
        "black",
        "black",
        "black",
        "green",
        "green",
        "green",
        "black",
        "light_green",
        "black",
        "white",
        "white",
        "white",
        "white",
        "white"
      ],
      [
        "white",
        "white",
        "white",
        "white",
        "black",
        "green",
        "green",
        "black",
        "light_green",
        "light_green",
        "black",
        "green",
        "green",
        "green",
        "black",
        "green",
        "green",
        "green",
        "black",
        "black",
        "black",
        "white",
        "white",
        "white",
        "white"
      ],
      [
        "white",
        "white",
        "white",
        "white",
        "black",
        "green",
        "green",
        "black",
        "light_green",
        "light_green",
        "black",
        "green",
        "green",
        "green",
        "green",
        "green",
        "black",
        "green",
        "green",
        "green",
        "black",
        "white",
        "white",
        "white",
        "white"
      ],
      [
        "white",
        "white",
        "white",
        "white",
        "white",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "white",
        "white",
        "white",
        "white",
        "white"
      ],
      [
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white"
      ]
    ]
  }
};
