window.PIXELFLOW_LEVEL_33 = {
  "id": "capybara",
  "name": "capybara",
  "fallbackFieldPattern": [
    "........................",
    "...........O9O..........",
    ".........9OOOO99........",
    "........949OO9449.......",
    "........994444449.......",
    "......99444444449.......",
    "....99444444444499......",
    "..994444444KK44499......",
    ".KKKKK444444444449......",
    ".KKKKK4444444444449.....",
    ".KKKKK4444444444449.....",
    ".9KKK444444449444499....",
    ".9444444444449444449DDD.",
    ".194444444449444444991CD",
    "DC1999444499444444499OOD",
    "DCC144999944444444499OOD",
    "DOO19444444444449999991D",
    "DOO119944444449OOO9991CD",
    "DCCCC1199999991OOO111CCD",
    ".DCCCCC1111111C1111CCCCD",
    ".DDCCCCCCCCCCCCCCCCCCDDD",
    "...DDDCCCCCCCCCCCDDDDD..",
    "......DDCCCCCCCDD.......",
    "........DDDDDDD........."
  ],
  "referenceGrid": {
    "x": 260,
    "y": 381,
    "step": 21,
    "cellSize": 19
  },
  "layout": {
    "fieldX": 260,
    "fieldY": 381,
    "fieldStep": 21,
    "cellSize": 19,
    "fieldCols": 24,
    "fieldRows": 24,
    "track": {
      "x": 106,
      "y": 189,
      "w": 808,
      "h": 856,
      "r": 50
    },
    "spawnPoint": {
      "x": 152,
      "y": 979
    },
    "cards": [
      {
        "lane": 0,
        "row": 0,
        "x": 312,
        "y": 1230,
        "w": 160,
        "h": 200,
        "color": "green",
        "styleKey": "mint",
        "label": 1,
        "ammo": 40
      },
      {
        "lane": 1,
        "row": 0,
        "x": 552,
        "y": 1230,
        "w": 160,
        "h": 200,
        "color": "black",
        "styleKey": "coral",
        "label": 2,
        "ammo": 40
      },
      {
        "lane": 0,
        "row": 1,
        "x": 312,
        "y": 1432,
        "w": 160,
        "h": 200,
        "color": "green",
        "styleKey": "sky",
        "label": 3,
        "ammo": 40
      },
      {
        "lane": 1,
        "row": 1,
        "x": 552,
        "y": 1432,
        "w": 160,
        "h": 200,
        "color": "black",
        "styleKey": "gold",
        "label": 4,
        "ammo": 40
      }
    ],
    "slots": [
      {
        "x": 98,
        "y": 1130,
        "w": 194,
        "h": 126
      },
      {
        "x": 311,
        "y": 1130,
        "w": 194,
        "h": 126
      },
      {
        "x": 520,
        "y": 1130,
        "w": 194,
        "h": 126
      },
      {
        "x": 729,
        "y": 1130,
        "w": 194,
        "h": 126
      }
    ],
    "wagonSprite": {
      "x": 44,
      "y": 840,
      "w": 148,
      "h": 116,
      "anchorX": 52,
      "anchorY": 96,
      "seatOffsetX": 0,
      "seatOffsetY": -52
    },
    "wagonMask": {
      "x": 0,
      "y": 820,
      "w": 260,
      "h": 200
    },
    "boardMask": {
      "x": 0,
      "y": 0,
      "w": 1024,
      "h": 1600,
      "r": 0
    }
  },
  "queueCardCount": 9,
  "pixelArt": {
    "id": "level-33-art",
    "name": "capybara_24х24.png",
    "sourceFileName": "capybara_24х24.png",
    "birdCount": 9,
    "artScale": 1,
    "offsetY": -37,
    "grid": {
      "cols": 24,
      "rows": 24
    },
    "pattern": [
      "........................",
      "...........O9O..........",
      ".........9OOOO99........",
      "........949OO9449.......",
      "........994444449.......",
      "......99444444449.......",
      "....99444444444499......",
      "..994444444KK44499......",
      ".KKKKK444444444449......",
      ".KKKKK4444444444449.....",
      ".KKKKK4444444444449.....",
      ".9KKK444444449444499....",
      ".9444444444449444449DDD.",
      ".194444444449444444991CD",
      "DC1999444499444444499OOD",
      "DCC144999944444444499OOD",
      "DOO19444444444449999991D",
      "DOO119944444449OOO9991CD",
      "DCCCC1199999991OOO111CCD",
      ".DCCCCC1111111C1111CCCCD",
      ".DDCCCCCCCCCCCCCCCCCCDDD",
      "...DDDCCCCCCCCCCCDDDDD..",
      "......DDCCCCCCCDD.......",
      "........DDDDDDD........."
    ],
    "colorMatrix": [
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "orange",
        "medium_brown",
        "orange",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "medium_brown",
        "orange",
        "orange",
        "orange",
        "orange",
        "medium_brown",
        "medium_brown",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "medium_brown",
        "light_brown",
        "medium_brown",
        "orange",
        "orange",
        "medium_brown",
        "light_brown",
        "light_brown",
        "medium_brown",
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "medium_brown",
        "medium_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "medium_brown",
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        "medium_brown",
        "medium_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "medium_brown",
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        "medium_brown",
        "medium_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "medium_brown",
        "medium_brown",
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        "medium_brown",
        "medium_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "black",
        "black",
        "light_brown",
        "light_brown",
        "light_brown",
        "medium_brown",
        "medium_brown",
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        "black",
        "black",
        "black",
        "black",
        "black",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "medium_brown",
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        "black",
        "black",
        "black",
        "black",
        "black",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "medium_brown",
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        "black",
        "black",
        "black",
        "black",
        "black",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "medium_brown",
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        "medium_brown",
        "black",
        "black",
        "black",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "medium_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "medium_brown",
        "medium_brown",
        null,
        null,
        null,
        null
      ],
      [
        null,
        "medium_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "medium_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "medium_brown",
        "dark_blue",
        "dark_blue",
        "dark_blue",
        null
      ],
      [
        null,
        "light_blue_1",
        "medium_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "medium_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "medium_brown",
        "medium_brown",
        "light_blue_1",
        "blue",
        "dark_blue"
      ],
      [
        "dark_blue",
        "blue",
        "light_blue_1",
        "medium_brown",
        "medium_brown",
        "medium_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "medium_brown",
        "medium_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "medium_brown",
        "medium_brown",
        "orange",
        "orange",
        "dark_blue"
      ],
      [
        "dark_blue",
        "blue",
        "blue",
        "light_blue_1",
        "light_brown",
        "light_brown",
        "medium_brown",
        "medium_brown",
        "medium_brown",
        "medium_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "medium_brown",
        "medium_brown",
        "orange",
        "orange",
        "dark_blue"
      ],
      [
        "dark_blue",
        "orange",
        "orange",
        "light_blue_1",
        "medium_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "medium_brown",
        "medium_brown",
        "medium_brown",
        "medium_brown",
        "medium_brown",
        "medium_brown",
        "light_blue_1",
        "dark_blue"
      ],
      [
        "dark_blue",
        "orange",
        "orange",
        "light_blue_1",
        "light_blue_1",
        "medium_brown",
        "medium_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "light_brown",
        "medium_brown",
        "orange",
        "orange",
        "orange",
        "medium_brown",
        "medium_brown",
        "medium_brown",
        "light_blue_1",
        "blue",
        "dark_blue"
      ],
      [
        "dark_blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "light_blue_1",
        "light_blue_1",
        "medium_brown",
        "medium_brown",
        "medium_brown",
        "medium_brown",
        "medium_brown",
        "medium_brown",
        "medium_brown",
        "light_blue_1",
        "orange",
        "orange",
        "orange",
        "light_blue_1",
        "light_blue_1",
        "light_blue_1",
        "blue",
        "blue",
        "dark_blue"
      ],
      [
        null,
        "dark_blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "light_blue_1",
        "light_blue_1",
        "light_blue_1",
        "light_blue_1",
        "light_blue_1",
        "light_blue_1",
        "light_blue_1",
        "blue",
        "light_blue_1",
        "light_blue_1",
        "light_blue_1",
        "light_blue_1",
        "blue",
        "blue",
        "blue",
        "blue",
        "dark_blue"
      ],
      [
        null,
        "dark_blue",
        "dark_blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "dark_blue",
        "dark_blue",
        "dark_blue"
      ],
      [
        null,
        null,
        null,
        "dark_blue",
        "dark_blue",
        "dark_blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "dark_blue",
        "dark_blue",
        "dark_blue",
        "dark_blue",
        "dark_blue",
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        "dark_blue",
        "dark_blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "dark_blue",
        "dark_blue",
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "dark_blue",
        "dark_blue",
        "dark_blue",
        "dark_blue",
        "dark_blue",
        "dark_blue",
        "dark_blue",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    ]
  },
  "levelNumber": 33,
  "debugOnly": false
};
