window.PIXELFLOW_LEVEL_7 = {
  "id": "7",
  "name": "Level 7",
  "fallbackFieldPattern": [
    "....................",
    "....................",
    "....................",
    ".DDDDDDDDDRRRRRRRRR.",
    ".DWDWDWDWDWWWWWWWWW.",
    ".DDWDWDWDDRRRRRRRRR.",
    ".DWDWDWDWDWWWWWWWWW.",
    ".DDWDWDWDDRRRRRRRRR.",
    ".DWDWDWDWDWWWWWWWWW.",
    ".DDDDDDDDDRRRRRRRRR.",
    ".WWWWWWWWWWWWWWWWWW.",
    ".RRRRRRRRRRRRRRRRRR.",
    ".WWWWWWWWWWWWWWWWWW.",
    ".RRRRRRRRRRRRRRRRRR.",
    ".WWWWWWWWWWWWWWWWWW.",
    ".RRRRRRRRRRRRRRRRRR.",
    "....................",
    "....................",
    "....................",
    "...................."
  ],
  "referenceGrid": {
    "x": 282,
    "y": 123,
    "step": 23,
    "cellSize": 21
  },
  "layout": {
    "fieldX": 282,
    "fieldY": 123,
    "fieldStep": 23,
    "cellSize": 21,
    "fieldCols": 20,
    "fieldRows": 20,
    "track": {
      "x": 106,
      "y": 189,
      "w": 808,
      "h": 856,
      "r": 50
    },
    "spawnPoint": {
      "x": 152,
      "y": 979
    },
    "cards": [
      {
        "lane": 0,
        "row": 0,
        "x": 312,
        "y": 1230,
        "w": 160,
        "h": 200,
        "color": "green",
        "styleKey": "mint",
        "label": 1,
        "ammo": 40
      },
      {
        "lane": 1,
        "row": 0,
        "x": 552,
        "y": 1230,
        "w": 160,
        "h": 200,
        "color": "black",
        "styleKey": "coral",
        "label": 2,
        "ammo": 40
      },
      {
        "lane": 0,
        "row": 1,
        "x": 312,
        "y": 1432,
        "w": 160,
        "h": 200,
        "color": "green",
        "styleKey": "sky",
        "label": 3,
        "ammo": 40
      },
      {
        "lane": 1,
        "row": 1,
        "x": 552,
        "y": 1432,
        "w": 160,
        "h": 200,
        "color": "black",
        "styleKey": "gold",
        "label": 4,
        "ammo": 40
      }
    ],
    "slots": [
      {
        "x": 98,
        "y": 1130,
        "w": 194,
        "h": 126
      },
      {
        "x": 311,
        "y": 1130,
        "w": 194,
        "h": 126
      },
      {
        "x": 520,
        "y": 1130,
        "w": 194,
        "h": 126
      },
      {
        "x": 729,
        "y": 1130,
        "w": 194,
        "h": 126
      }
    ],
    "wagonSprite": {
      "x": 44,
      "y": 840,
      "w": 148,
      "h": 116,
      "anchorX": 52,
      "anchorY": 96,
      "seatOffsetX": 0,
      "seatOffsetY": -52
    },
    "wagonMask": {
      "x": 0,
      "y": 820,
      "w": 260,
      "h": 200
    },
    "boardMask": {
      "x": 0,
      "y": 0,
      "w": 1024,
      "h": 1600,
      "r": 0
    }
  },
  "queueCardCount": 7,
  "pixelArt": {
    "id": "level-7-art",
    "name": "flag_USA.png",
    "sourceFileName": "flag_USA.png",
    "artScale": 1,
    "offsetY": -37,
    "grid": {
      "cols": 20,
      "rows": 20
    },
    "pattern": [
      "....................",
      "....................",
      "....................",
      ".DDDDDDDDDRRRRRRRRR.",
      ".DWDWDWDWDWWWWWWWWW.",
      ".DDWDWDWDDRRRRRRRRR.",
      ".DWDWDWDWDWWWWWWWWW.",
      ".DDWDWDWDDRRRRRRRRR.",
      ".DWDWDWDWDWWWWWWWWW.",
      ".DDDDDDDDDRRRRRRRRR.",
      ".WWWWWWWWWWWWWWWWWW.",
      ".RRRRRRRRRRRRRRRRRR.",
      ".WWWWWWWWWWWWWWWWWW.",
      ".RRRRRRRRRRRRRRRRRR.",
      ".WWWWWWWWWWWWWWWWWW.",
      ".RRRRRRRRRRRRRRRRRR.",
      "....................",
      "....................",
      "....................",
      "...................."
    ],
    "colorMatrix": [
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        "dark_blue",
        "dark_blue",
        "dark_blue",
        "dark_blue",
        "dark_blue",
        "dark_blue",
        "dark_blue",
        "dark_blue",
        "dark_blue",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        null
      ],
      [
        null,
        "dark_blue",
        "white",
        "dark_blue",
        "white",
        "dark_blue",
        "white",
        "dark_blue",
        "white",
        "dark_blue",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        null
      ],
      [
        null,
        "dark_blue",
        "dark_blue",
        "white",
        "dark_blue",
        "white",
        "dark_blue",
        "white",
        "dark_blue",
        "dark_blue",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        null
      ],
      [
        null,
        "dark_blue",
        "white",
        "dark_blue",
        "white",
        "dark_blue",
        "white",
        "dark_blue",
        "white",
        "dark_blue",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        null
      ],
      [
        null,
        "dark_blue",
        "dark_blue",
        "white",
        "dark_blue",
        "white",
        "dark_blue",
        "white",
        "dark_blue",
        "dark_blue",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        null
      ],
      [
        null,
        "dark_blue",
        "white",
        "dark_blue",
        "white",
        "dark_blue",
        "white",
        "dark_blue",
        "white",
        "dark_blue",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        null
      ],
      [
        null,
        "dark_blue",
        "dark_blue",
        "dark_blue",
        "dark_blue",
        "dark_blue",
        "dark_blue",
        "dark_blue",
        "dark_blue",
        "dark_blue",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        null
      ],
      [
        null,
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        null
      ],
      [
        null,
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        null
      ],
      [
        null,
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        null
      ],
      [
        null,
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        null
      ],
      [
        null,
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        null
      ],
      [
        null,
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    ]
  }
};
