window.PIXELFLOW_LEVEL_5 = {
  "id": "5",
  "name": "Level 5",
  "fallbackFieldPattern": [
    ".....KKKK......",
    "....KYYYYK.....",
    "...KYYYYYYK....",
    "...KYYKYYYK....",
    ".KKKRYKKYYK....",
    "KRRRRYYYYYK...K",
    ".KKRRRYYYK...KK",
    "...KKRRYK...KYK",
    "...KYYYYYKKKYYK",
    "..KYYYRYYYYYYYK",
    "..KYYYYRYYYRYYK",
    "..KYYYYYRRRYYYK",
    "...KYYYYYYYYYK.",
    "....KRRKRRRKK..",
    ".....KKKKKKK..."
  ],
  "referenceGrid": {
    "x": 190,
    "y": 385,
    "step": 43,
    "cellSize": 39
  },
  "layout": {
    "fieldX": 190,
    "fieldY": 385,
    "fieldStep": 43,
    "cellSize": 39,
    "fieldCols": 15,
    "fieldRows": 15,
    "track": {
      "x": 106,
      "y": 189,
      "w": 808,
      "h": 856,
      "r": 50
    },
    "spawnPoint": {
      "x": 152,
      "y": 979
    },
    "cards": [
      {
        "lane": 0,
        "row": 0,
        "x": 312,
        "y": 1230,
        "w": 160,
        "h": 200,
        "color": "green",
        "styleKey": "mint",
        "label": 1,
        "ammo": 40
      },
      {
        "lane": 1,
        "row": 0,
        "x": 552,
        "y": 1230,
        "w": 160,
        "h": 200,
        "color": "black",
        "styleKey": "coral",
        "label": 2,
        "ammo": 40
      },
      {
        "lane": 0,
        "row": 1,
        "x": 312,
        "y": 1432,
        "w": 160,
        "h": 200,
        "color": "green",
        "styleKey": "sky",
        "label": 3,
        "ammo": 40
      },
      {
        "lane": 1,
        "row": 1,
        "x": 552,
        "y": 1432,
        "w": 160,
        "h": 200,
        "color": "black",
        "styleKey": "gold",
        "label": 4,
        "ammo": 40
      }
    ],
    "slots": [
      {
        "x": 98,
        "y": 1130,
        "w": 194,
        "h": 126
      },
      {
        "x": 311,
        "y": 1130,
        "w": 194,
        "h": 126
      },
      {
        "x": 520,
        "y": 1130,
        "w": 194,
        "h": 126
      },
      {
        "x": 729,
        "y": 1130,
        "w": 194,
        "h": 126
      }
    ],
    "wagonSprite": {
      "x": 44,
      "y": 840,
      "w": 148,
      "h": 116,
      "anchorX": 52,
      "anchorY": 96,
      "seatOffsetX": 0,
      "seatOffsetY": -52
    },
    "wagonMask": {
      "x": 0,
      "y": 820,
      "w": 260,
      "h": 200
    },
    "boardMask": {
      "x": 0,
      "y": 0,
      "w": 1024,
      "h": 1600,
      "r": 0
    }
  },
  "queueCardCount": 7,
  "pixelArt": {
    "id": "level-5-art",
    "name": "36b8c917-7e98-4de6-8d25-aac290041817.png",
    "sourceFileName": "36b8c917-7e98-4de6-8d25-aac290041817.png",
    "artScale": 0.9,
    "offsetY": -37,
    "grid": {
      "cols": 15,
      "rows": 15
    },
    "pattern": [
      ".....KKKK......",
      "....KYYYYK.....",
      "...KYYYYYYK....",
      "...KYYKYYYK....",
      ".KKKRYKKYYK....",
      "KRRRRYYYYYK...K",
      ".KKRRRYYYK...KK",
      "...KKRRYK...KYK",
      "...KYYYYYKKKYYK",
      "..KYYYRYYYYYYYK",
      "..KYYYYRYYYRYYK",
      "..KYYYYYRRRYYYK",
      "...KYYYYYYYYYK.",
      "....KRRKRRRKK..",
      ".....KKKKKKK..."
    ],
    "colorMatrix": [
      [
        null,
        null,
        null,
        null,
        null,
        "black",
        "black",
        "black",
        "black",
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        "black",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "black",
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        "black",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "black",
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        "black",
        "yellow",
        "yellow",
        "black",
        "yellow",
        "yellow",
        "yellow",
        "black",
        null,
        null,
        null,
        null
      ],
      [
        null,
        "black",
        "black",
        "black",
        "red",
        "yellow",
        "black",
        "black",
        "yellow",
        "yellow",
        "black",
        null,
        null,
        null,
        null
      ],
      [
        "black",
        "red",
        "red",
        "red",
        "red",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "black",
        null,
        null,
        null,
        "black"
      ],
      [
        null,
        "black",
        "black",
        "red",
        "red",
        "red",
        "yellow",
        "yellow",
        "yellow",
        "black",
        null,
        null,
        null,
        "black",
        "black"
      ],
      [
        null,
        null,
        null,
        "black",
        "black",
        "red",
        "red",
        "yellow",
        "black",
        null,
        null,
        null,
        "black",
        "yellow",
        "black"
      ],
      [
        null,
        null,
        null,
        "black",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "black",
        "black",
        "black",
        "yellow",
        "yellow",
        "black"
      ],
      [
        null,
        null,
        "black",
        "yellow",
        "yellow",
        "yellow",
        "red",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "black"
      ],
      [
        null,
        null,
        "black",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "red",
        "yellow",
        "yellow",
        "yellow",
        "red",
        "yellow",
        "yellow",
        "black"
      ],
      [
        null,
        null,
        "black",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "red",
        "red",
        "red",
        "yellow",
        "yellow",
        "yellow",
        "black"
      ],
      [
        null,
        null,
        null,
        "black",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "black",
        null
      ],
      [
        null,
        null,
        null,
        null,
        "black",
        "red",
        "red",
        "black",
        "red",
        "red",
        "red",
        "black",
        "black",
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        null,
        null,
        null
      ]
    ],
    "birdCount": 7
  }
};
