window.PIXELFLOW_LEVEL_8 = {
  "id": "8",
  "name": "earth",
  "displayName": "Earth",
  "fallbackFieldPattern": [
    "......KKKKKK......",
    "....KKGCCCCGKK....",
    "...KGGCCCCGGGGK...",
    "..KGGCCCCGGGGGGK..",
    ".KCCCCCCGGGGGGGGK.",
    ".KCCCCGCCCGGGGGGK.",
    "KCCCCGGGCCCGCCGGGK",
    "KCCCGGGGGGGCCCCCGK",
    "KCCGGGGGGGCCCCCCCK",
    "KCCCGGGGGGGCCCCCCK",
    "KGCCCCGGGGGGGCCCDK",
    "KGCCCCCGGGGGCCCDDK",
    ".KGCCCCCGGGCCCDDK.",
    ".KGDCCCCGGCCCDDDK.",
    "..KDDCCCGGCCDDDK..",
    "...KDDDDGDDDDDK...",
    "....KKDDDDDDKK....",
    "......KKKKKK......"
  ],
  "referenceGrid": {
    "x": 224,
    "y": 382,
    "step": 32,
    "cellSize": 29
  },
  "layout": {
    "fieldX": 224,
    "fieldY": 382,
    "fieldStep": 32,
    "cellSize": 29,
    "fieldCols": 18,
    "fieldRows": 18,
    "track": {
      "x": 106,
      "y": 189,
      "w": 808,
      "h": 856,
      "r": 50
    },
    "spawnPoint": {
      "x": 152,
      "y": 979
    },
    "cards": [
      {
        "lane": 0,
        "row": 0,
        "x": 312,
        "y": 1230,
        "w": 160,
        "h": 200,
        "color": "green",
        "styleKey": "mint",
        "label": 1,
        "ammo": 40
      },
      {
        "lane": 1,
        "row": 0,
        "x": 552,
        "y": 1230,
        "w": 160,
        "h": 200,
        "color": "black",
        "styleKey": "coral",
        "label": 2,
        "ammo": 40
      },
      {
        "lane": 0,
        "row": 1,
        "x": 312,
        "y": 1432,
        "w": 160,
        "h": 200,
        "color": "green",
        "styleKey": "sky",
        "label": 3,
        "ammo": 40
      },
      {
        "lane": 1,
        "row": 1,
        "x": 552,
        "y": 1432,
        "w": 160,
        "h": 200,
        "color": "black",
        "styleKey": "gold",
        "label": 4,
        "ammo": 40
      }
    ],
    "slots": [
      {
        "x": 98,
        "y": 1130,
        "w": 194,
        "h": 126
      },
      {
        "x": 311,
        "y": 1130,
        "w": 194,
        "h": 126
      },
      {
        "x": 520,
        "y": 1130,
        "w": 194,
        "h": 126
      },
      {
        "x": 729,
        "y": 1130,
        "w": 194,
        "h": 126
      }
    ],
    "wagonSprite": {
      "x": 44,
      "y": 840,
      "w": 148,
      "h": 116,
      "anchorX": 52,
      "anchorY": 96,
      "seatOffsetX": 0,
      "seatOffsetY": -52
    },
    "wagonMask": {
      "x": 0,
      "y": 820,
      "w": 260,
      "h": 200
    },
    "boardMask": {
      "x": 0,
      "y": 0,
      "w": 1024,
      "h": 1600,
      "r": 0
    }
  },
  "queueCardCount": 7,
  "pixelArt": {
    "id": "level-8-art",
    "name": "36b8c917-7e98-4de6-8d25-aac290041817.png",
    "sourceFileName": "36b8c917-7e98-4de6-8d25-aac290041817.png",
    "artScale": 1,
    "offsetY": -37,
    "grid": {
      "cols": 18,
      "rows": 18
    },
    "pattern": [
      "......KKKKKK......",
      "....KKGCCCCGKK....",
      "...KGGCCCCGGGGK...",
      "..KGGCCCCGGGGGGK..",
      ".KCCCCCCGGGGGGGGK.",
      ".KCCCCGCCCGGGGGGK.",
      "KCCCCGGGCCCGCCGGGK",
      "KCCCGGGGGGGCCCCCGK",
      "KCCGGGGGGGCCCCCCCK",
      "KCCCGGGGGGGCCCCCCK",
      "KGCCCCGGGGGGGCCCDK",
      "KGCCCCCGGGGGCCCDDK",
      ".KGCCCCCGGGCCCDDK.",
      ".KGDCCCCGGCCCDDDK.",
      "..KDDCCCGGCCDDDK..",
      "...KDDDDGDDDDDK...",
      "....KKDDDDDDKK....",
      "......KKKKKK......"
    ],
    "colorMatrix": [
      [
        null,
        null,
        null,
        null,
        null,
        null,
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        "black",
        "black",
        "green",
        "blue",
        "blue",
        "blue",
        "blue",
        "green",
        "black",
        "black",
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        "black",
        "green",
        "green",
        "blue",
        "blue",
        "blue",
        "blue",
        "green",
        "green",
        "green",
        "green",
        "black",
        null,
        null,
        null
      ],
      [
        null,
        null,
        "black",
        "green",
        "green",
        "blue",
        "blue",
        "blue",
        "blue",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "black",
        null,
        null
      ],
      [
        null,
        "black",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "black",
        null
      ],
      [
        null,
        "black",
        "blue",
        "blue",
        "blue",
        "blue",
        "green",
        "blue",
        "blue",
        "blue",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "black",
        null
      ],
      [
        "black",
        "blue",
        "blue",
        "blue",
        "blue",
        "green",
        "green",
        "green",
        "blue",
        "blue",
        "blue",
        "green",
        "blue",
        "blue",
        "green",
        "green",
        "green",
        "black"
      ],
      [
        "black",
        "blue",
        "blue",
        "blue",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "green",
        "black"
      ],
      [
        "black",
        "blue",
        "blue",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "black"
      ],
      [
        "black",
        "blue",
        "blue",
        "blue",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "black"
      ],
      [
        "black",
        "green",
        "blue",
        "blue",
        "blue",
        "blue",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "blue",
        "blue",
        "blue",
        "dark_blue",
        "black"
      ],
      [
        "black",
        "green",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "green",
        "green",
        "green",
        "green",
        "green",
        "blue",
        "blue",
        "blue",
        "dark_blue",
        "dark_blue",
        "black"
      ],
      [
        null,
        "black",
        "green",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "green",
        "green",
        "green",
        "blue",
        "blue",
        "blue",
        "dark_blue",
        "dark_blue",
        "black",
        null
      ],
      [
        null,
        "black",
        "green",
        "dark_blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "green",
        "green",
        "blue",
        "blue",
        "blue",
        "dark_blue",
        "dark_blue",
        "dark_blue",
        "black",
        null
      ],
      [
        null,
        null,
        "black",
        "dark_blue",
        "dark_blue",
        "blue",
        "blue",
        "blue",
        "green",
        "green",
        "blue",
        "blue",
        "dark_blue",
        "dark_blue",
        "dark_blue",
        "black",
        null,
        null
      ],
      [
        null,
        null,
        null,
        "black",
        "dark_blue",
        "dark_blue",
        "dark_blue",
        "dark_blue",
        "green",
        "dark_blue",
        "dark_blue",
        "dark_blue",
        "dark_blue",
        "dark_blue",
        "black",
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        "black",
        "black",
        "dark_blue",
        "dark_blue",
        "dark_blue",
        "dark_blue",
        "dark_blue",
        "dark_blue",
        "black",
        "black",
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        null,
        null,
        null,
        null,
        null,
        null
      ]
    ],
    "birdCount": 7
  }
};
