window.PIXELFLOW_LEVEL_32 = {
  "id": "sakura",
  "name": "sakura",
  "displayName": "Sakura",
  "fallbackFieldPattern": [
    "..............................",
    "...........77.77..............",
    "..........76676677778.........",
    ".........7666666766678........",
    "........76666666666678........",
    ".......76667667666677787......",
    "......866776676666777867......",
    "......7877777777787787668.....",
    "....7767888777788766666678....",
    "...766666778887K7666667677H...",
    "..7666666777K888666667677HHH..",
    "..66667766677KKH7678777778778.",
    ".77766776677HHK877777777866678",
    ".87777877H778HKK778H7887666778",
    "..8HHHHHH878H8.K888K777776687H",
    ".76678HKK88888.KKHK88777H7778H",
    "8666777H8K8K..99KK88HKKH77H8H8",
    "8778H7H8H8K9..K9KH86KK887H888.",
    ".888HH88H8.KKK9K77.KK888HHH8..",
    "..H8.88H.....99KKKK...88.88...",
    "...8.....6...999KK.....8......",
    "......8......9KK...H.6....8...",
    "...7........99K...............",
    ".........8..99K.......8.......",
    "......6....K999KK...6..6......",
    "..........299K9KK.............",
    ".......78899KKK9KK82882.......",
    "....K282K9K8888K998K87872.....",
    "....886876862278768278777.....",
    ".............................."
  ],
  "referenceGrid": {
    "x": 257,
    "y": 415,
    "step": 17,
    "cellSize": 15
  },
  "layout": {
    "fieldX": 257,
    "fieldY": 415,
    "fieldStep": 17,
    "cellSize": 15,
    "fieldCols": 30,
    "fieldRows": 30,
    "track": {
      "x": 106,
      "y": 189,
      "w": 808,
      "h": 856,
      "r": 50
    },
    "spawnPoint": {
      "x": 152,
      "y": 979
    },
    "cards": [
      {
        "lane": 0,
        "row": 0,
        "x": 312,
        "y": 1230,
        "w": 160,
        "h": 200,
        "color": "green",
        "styleKey": "mint",
        "label": 1,
        "ammo": 40
      },
      {
        "lane": 1,
        "row": 0,
        "x": 552,
        "y": 1230,
        "w": 160,
        "h": 200,
        "color": "black",
        "styleKey": "coral",
        "label": 2,
        "ammo": 40
      },
      {
        "lane": 0,
        "row": 1,
        "x": 312,
        "y": 1432,
        "w": 160,
        "h": 200,
        "color": "green",
        "styleKey": "sky",
        "label": 3,
        "ammo": 40
      },
      {
        "lane": 1,
        "row": 1,
        "x": 552,
        "y": 1432,
        "w": 160,
        "h": 200,
        "color": "black",
        "styleKey": "gold",
        "label": 4,
        "ammo": 40
      }
    ],
    "slots": [
      {
        "x": 98,
        "y": 1130,
        "w": 194,
        "h": 126
      },
      {
        "x": 311,
        "y": 1130,
        "w": 194,
        "h": 126
      },
      {
        "x": 520,
        "y": 1130,
        "w": 194,
        "h": 126
      },
      {
        "x": 729,
        "y": 1130,
        "w": 194,
        "h": 126
      }
    ],
    "wagonSprite": {
      "x": 44,
      "y": 840,
      "w": 148,
      "h": 116,
      "anchorX": 52,
      "anchorY": 96,
      "seatOffsetX": 0,
      "seatOffsetY": -52
    },
    "wagonMask": {
      "x": 0,
      "y": 820,
      "w": 260,
      "h": 200
    },
    "boardMask": {
      "x": 0,
      "y": 0,
      "w": 1024,
      "h": 1600,
      "r": 0
    }
  },
  "queueCardCount": 9,
  "pixelArt": {
    "id": "level-32-art",
    "name": "sakura_30х30.png",
    "sourceFileName": "sakura_30х30.png",
    "birdCount": 9,
    "artScale": 1,
    "offsetY": -37,
    "grid": {
      "cols": 30,
      "rows": 30
    },
    "pattern": [
      "..............................",
      "...........77.77..............",
      "..........76676677778.........",
      ".........7666666766678........",
      "........76666666666678........",
      ".......76667667666677787......",
      "......866776676666777867......",
      "......7877777777787787668.....",
      "....7767888777788766666678....",
      "...766666778887K7666667677H...",
      "..7666666777K888666667677HHH..",
      "..66667766677KKH7678777778778.",
      ".77766776677HHK877777777866678",
      ".87777877H778HKK778H7887666778",
      "..8HHHHHH878H8.K888K777776687H",
      ".76678HKK88888.KKHK88777H7778H",
      "8666777H8K8K..99KK88HKKH77H8H8",
      "8778H7H8H8K9..K9KH86KK887H888.",
      ".888HH88H8.KKK9K77.KK888HHH8..",
      "..H8.88H.....99KKKK...88.88...",
      "...8.....6...999KK.....8......",
      "......8......9KK...H.6....8...",
      "...7........99K...............",
      ".........8..99K.......8.......",
      "......6....K999KK...6..6......",
      "..........299K9KK.............",
      ".......78899KKK9KK82882.......",
      "....K282K9K8888K998K87872.....",
      "....886876862278768278777.....",
      ".............................."
    ],
    "colorMatrix": [
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "light_pink_2",
        "light_pink_2",
        null,
        "light_pink_2",
        "light_pink_2",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "light_pink_2",
        "light_pink_1",
        "light_pink_1",
        "light_pink_2",
        "light_pink_1",
        "light_pink_1",
        "light_pink_2",
        "light_pink_2",
        "light_pink_2",
        "light_pink_2",
        "light_pink_3",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "light_pink_2",
        "light_pink_1",
        "light_pink_1",
        "light_pink_1",
        "light_pink_1",
        "light_pink_1",
        "light_pink_1",
        "light_pink_2",
        "light_pink_1",
        "light_pink_1",
        "light_pink_1",
        "light_pink_2",
        "light_pink_3",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "light_pink_2",
        "light_pink_1",
        "light_pink_1",
        "light_pink_1",
        "light_pink_1",
        "light_pink_1",
        "light_pink_1",
        "light_pink_1",
        "light_pink_1",
        "light_pink_1",
        "light_pink_1",
        "light_pink_1",
        "light_pink_2",
        "light_pink_3",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "light_pink_2",
        "light_pink_1",
        "light_pink_1",
        "light_pink_1",
        "light_pink_2",
        "light_pink_1",
        "light_pink_1",
        "light_pink_2",
        "light_pink_1",
        "light_pink_1",
        "light_pink_1",
        "light_pink_1",
        "light_pink_2",
        "light_pink_2",
        "light_pink_2",
        "light_pink_3",
        "light_pink_2",
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        "light_pink_3",
        "light_pink_1",
        "light_pink_1",
        "light_pink_2",
        "light_pink_2",
        "light_pink_1",
        "light_pink_1",
        "light_pink_2",
        "light_pink_1",
        "light_pink_1",
        "light_pink_1",
        "light_pink_1",
        "light_pink_2",
        "light_pink_2",
        "light_pink_2",
        "light_pink_3",
        "light_pink_1",
        "light_pink_2",
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        "light_pink_2",
        "light_pink_3",
        "light_pink_2",
        "light_pink_2",
        "light_pink_2",
        "light_pink_2",
        "light_pink_2",
        "light_pink_2",
        "light_pink_2",
        "light_pink_2",
        "light_pink_2",
        "light_pink_3",
        "light_pink_2",
        "light_pink_2",
        "light_pink_3",
        "light_pink_2",
        "light_pink_1",
        "light_pink_1",
        "light_pink_3",
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        "light_pink_2",
        "light_pink_2",
        "light_pink_1",
        "light_pink_2",
        "light_pink_3",
        "light_pink_3",
        "light_pink_3",
        "light_pink_2",
        "light_pink_2",
        "light_pink_2",
        "light_pink_2",
        "light_pink_3",
        "light_pink_3",
        "light_pink_2",
        "light_pink_1",
        "light_pink_1",
        "light_pink_1",
        "light_pink_1",
        "light_pink_1",
        "light_pink_1",
        "light_pink_2",
        "light_pink_3",
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        "light_pink_2",
        "light_pink_1",
        "light_pink_1",
        "light_pink_1",
        "light_pink_1",
        "light_pink_1",
        "light_pink_2",
        "light_pink_2",
        "light_pink_3",
        "light_pink_3",
        "light_pink_3",
        "light_pink_2",
        "black",
        "light_pink_2",
        "light_pink_1",
        "light_pink_1",
        "light_pink_1",
        "light_pink_1",
        "light_pink_1",
        "light_pink_2",
        "light_pink_1",
        "light_pink_2",
        "light_pink_2",
        "red_alt",
        null,
        null,
        null
      ],
      [
        null,
        null,
        "light_pink_2",
        "light_pink_1",
        "light_pink_1",
        "light_pink_1",
        "light_pink_1",
        "light_pink_1",
        "light_pink_1",
        "light_pink_2",
        "light_pink_2",
        "light_pink_2",
        "black",
        "light_pink_3",
        "light_pink_3",
        "light_pink_3",
        "light_pink_1",
        "light_pink_1",
        "light_pink_1",
        "light_pink_1",
        "light_pink_1",
        "light_pink_2",
        "light_pink_1",
        "light_pink_2",
        "light_pink_2",
        "red_alt",
        "red_alt",
        "red_alt",
        null,
        null
      ],
      [
        null,
        null,
        "light_pink_1",
        "light_pink_1",
        "light_pink_1",
        "light_pink_1",
        "light_pink_2",
        "light_pink_2",
        "light_pink_1",
        "light_pink_1",
        "light_pink_1",
        "light_pink_2",
        "light_pink_2",
        "black",
        "black",
        "red_alt",
        "light_pink_2",
        "light_pink_1",
        "light_pink_2",
        "light_pink_3",
        "light_pink_2",
        "light_pink_2",
        "light_pink_2",
        "light_pink_2",
        "light_pink_2",
        "light_pink_3",
        "light_pink_2",
        "light_pink_2",
        "light_pink_3",
        null
      ],
      [
        null,
        "light_pink_2",
        "light_pink_2",
        "light_pink_2",
        "light_pink_1",
        "light_pink_1",
        "light_pink_2",
        "light_pink_2",
        "light_pink_1",
        "light_pink_1",
        "light_pink_2",
        "light_pink_2",
        "red_alt",
        "red_alt",
        "black",
        "light_pink_3",
        "light_pink_2",
        "light_pink_2",
        "light_pink_2",
        "light_pink_2",
        "light_pink_2",
        "light_pink_2",
        "light_pink_2",
        "light_pink_2",
        "light_pink_3",
        "light_pink_1",
        "light_pink_1",
        "light_pink_1",
        "light_pink_2",
        "light_pink_3"
      ],
      [
        null,
        "light_pink_3",
        "light_pink_2",
        "light_pink_2",
        "light_pink_2",
        "light_pink_2",
        "light_pink_3",
        "light_pink_2",
        "light_pink_2",
        "red_alt",
        "light_pink_2",
        "light_pink_2",
        "light_pink_3",
        "red_alt",
        "black",
        "black",
        "light_pink_2",
        "light_pink_2",
        "light_pink_3",
        "red_alt",
        "light_pink_2",
        "light_pink_3",
        "light_pink_3",
        "light_pink_2",
        "light_pink_1",
        "light_pink_1",
        "light_pink_1",
        "light_pink_2",
        "light_pink_2",
        "light_pink_3"
      ],
      [
        null,
        null,
        "light_pink_3",
        "red_alt",
        "red_alt",
        "red_alt",
        "red_alt",
        "red_alt",
        "red_alt",
        "light_pink_3",
        "light_pink_2",
        "light_pink_3",
        "red_alt",
        "light_pink_3",
        null,
        "black",
        "light_pink_3",
        "light_pink_3",
        "light_pink_3",
        "black",
        "light_pink_2",
        "light_pink_2",
        "light_pink_2",
        "light_pink_2",
        "light_pink_2",
        "light_pink_1",
        "light_pink_1",
        "light_pink_3",
        "light_pink_2",
        "red_alt"
      ],
      [
        null,
        "light_pink_2",
        "light_pink_1",
        "light_pink_1",
        "light_pink_2",
        "light_pink_3",
        "red_alt",
        "black",
        "black",
        "light_pink_3",
        "light_pink_3",
        "light_pink_3",
        "light_pink_3",
        "light_pink_3",
        null,
        "black",
        "black",
        "red_alt",
        "black",
        "light_pink_3",
        "light_pink_3",
        "light_pink_2",
        "light_pink_2",
        "light_pink_2",
        "red_alt",
        "light_pink_2",
        "light_pink_2",
        "light_pink_2",
        "light_pink_3",
        "red_alt"
      ],
      [
        "light_pink_3",
        "light_pink_1",
        "light_pink_1",
        "light_pink_1",
        "light_pink_2",
        "light_pink_2",
        "light_pink_2",
        "red_alt",
        "light_pink_3",
        "black",
        "light_pink_3",
        "black",
        null,
        null,
        "medium_brown",
        "medium_brown",
        "black",
        "black",
        "light_pink_3",
        "light_pink_3",
        "red_alt",
        "black",
        "black",
        "red_alt",
        "light_pink_2",
        "light_pink_2",
        "red_alt",
        "light_pink_3",
        "red_alt",
        "light_pink_3"
      ],
      [
        "light_pink_3",
        "light_pink_2",
        "light_pink_2",
        "light_pink_3",
        "red_alt",
        "light_pink_2",
        "red_alt",
        "light_pink_3",
        "red_alt",
        "light_pink_3",
        "black",
        "medium_brown",
        null,
        null,
        "black",
        "medium_brown",
        "black",
        "red_alt",
        "light_pink_3",
        "light_pink_1",
        "black",
        "black",
        "light_pink_3",
        "light_pink_3",
        "light_pink_2",
        "red_alt",
        "light_pink_3",
        "light_pink_3",
        "light_pink_3",
        null
      ],
      [
        null,
        "light_pink_3",
        "light_pink_3",
        "light_pink_3",
        "red_alt",
        "red_alt",
        "light_pink_3",
        "light_pink_3",
        "red_alt",
        "light_pink_3",
        null,
        "black",
        "black",
        "black",
        "medium_brown",
        "black",
        "light_pink_2",
        "light_pink_2",
        null,
        "black",
        "black",
        "light_pink_3",
        "light_pink_3",
        "light_pink_3",
        "red_alt",
        "red_alt",
        "red_alt",
        "light_pink_3",
        null,
        null
      ],
      [
        null,
        null,
        "red_alt",
        "light_pink_3",
        null,
        "light_pink_3",
        "light_pink_3",
        "red_alt",
        null,
        null,
        null,
        null,
        null,
        "medium_brown",
        "medium_brown",
        "black",
        "black",
        "black",
        "black",
        null,
        null,
        null,
        "light_pink_3",
        "light_pink_3",
        null,
        "light_pink_3",
        "light_pink_3",
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        "light_pink_3",
        null,
        null,
        null,
        null,
        null,
        "light_pink_1",
        null,
        null,
        null,
        "medium_brown",
        "medium_brown",
        "medium_brown",
        "black",
        "black",
        null,
        null,
        null,
        null,
        null,
        "light_pink_3",
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        "light_pink_3",
        null,
        null,
        null,
        null,
        null,
        null,
        "medium_brown",
        "black",
        "black",
        null,
        null,
        null,
        "red_alt",
        null,
        "light_pink_1",
        null,
        null,
        null,
        null,
        "light_pink_3",
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        "light_pink_2",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "medium_brown",
        "medium_brown",
        "black",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "light_pink_3",
        null,
        null,
        "medium_brown",
        "medium_brown",
        "black",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "light_pink_3",
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        "light_pink_1",
        null,
        null,
        null,
        null,
        "black",
        "medium_brown",
        "medium_brown",
        "medium_brown",
        "black",
        "black",
        null,
        null,
        null,
        "light_pink_1",
        null,
        null,
        "light_pink_1",
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "light_blue",
        "medium_brown",
        "medium_brown",
        "black",
        "medium_brown",
        "black",
        "black",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "light_pink_2",
        "light_pink_3",
        "light_pink_3",
        "medium_brown",
        "medium_brown",
        "black",
        "black",
        "black",
        "medium_brown",
        "black",
        "black",
        "light_pink_3",
        "light_blue",
        "light_pink_3",
        "light_pink_3",
        "light_blue",
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        "black",
        "light_blue",
        "light_pink_3",
        "light_blue",
        "black",
        "medium_brown",
        "black",
        "light_pink_3",
        "light_pink_3",
        "light_pink_3",
        "light_pink_3",
        "black",
        "medium_brown",
        "medium_brown",
        "light_pink_3",
        "black",
        "light_pink_3",
        "light_pink_2",
        "light_pink_3",
        "light_pink_2",
        "light_blue",
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        "light_pink_3",
        "light_pink_3",
        "light_pink_1",
        "light_pink_3",
        "light_pink_2",
        "light_pink_1",
        "light_pink_3",
        "light_pink_1",
        "light_blue",
        "light_blue",
        "light_pink_2",
        "light_pink_3",
        "light_pink_2",
        "light_pink_1",
        "light_pink_3",
        "light_blue",
        "light_pink_2",
        "light_pink_3",
        "light_pink_2",
        "light_pink_2",
        "light_pink_2",
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    ]
  },
  "levelNumber": 32,
  "debugOnly": false
};
