window.PIXELFLOW_LEVEL_11 = {
  "id": "11",
  "name": "proposal",
  "displayName": "Proposal",
  "fallbackFieldPattern": [
    "....KKKKKKKKK....",
    "...KRRRRRRRRRK...",
    "..KRRKKKKKKKRRK..",
    ".KRRKWWWWWWWKRRK.",
    "KRRKWWWWWWWWWKRRK",
    "KRKWWWWWWWWWWWKRK",
    "KRKWWWWWWWWWWWKRK",
    "KRKWWWKWWWKWWWKRK",
    ".KRKWKEKWKEKWKRK.",
    "..KKKEEEKEEEKKK..",
    ".KKKYKEEEEEKYKKK.",
    "KRKYKKKEEEKKKYKRK",
    "KRKYEEEKEKEEEYKRK",
    "KREKYYYEKEYYYKERK",
    "KREEKKYYYYYKKEERK",
    "KKEEEEKKKKKEEEEKK",
    "KRKEEEEEEEEEEEKRK",
    "KRRKKKKKKKKKKKRRK",
    ".KRRRRRRRRRRRRRK.",
    "..KRRRRRRRRRRRK..",
    "...KKKKKKKKKKK..."
  ],
  "referenceGrid": {
    "x": 291,
    "y": 434,
    "step": 26,
    "cellSize": 24
  },
  "layout": {
    "fieldX": 291,
    "fieldY": 434,
    "fieldStep": 26,
    "cellSize": 24,
    "fieldCols": 17,
    "fieldRows": 21,
    "track": {
      "x": 106,
      "y": 189,
      "w": 808,
      "h": 856,
      "r": 50
    },
    "spawnPoint": {
      "x": 152,
      "y": 979
    },
    "cards": [
      {
        "lane": 0,
        "row": 0,
        "x": 312,
        "y": 1230,
        "w": 160,
        "h": 200,
        "color": "green",
        "styleKey": "mint",
        "label": 1,
        "ammo": 40
      },
      {
        "lane": 1,
        "row": 0,
        "x": 552,
        "y": 1230,
        "w": 160,
        "h": 200,
        "color": "black",
        "styleKey": "coral",
        "label": 2,
        "ammo": 40
      },
      {
        "lane": 0,
        "row": 1,
        "x": 312,
        "y": 1432,
        "w": 160,
        "h": 200,
        "color": "green",
        "styleKey": "sky",
        "label": 3,
        "ammo": 40
      },
      {
        "lane": 1,
        "row": 1,
        "x": 552,
        "y": 1432,
        "w": 160,
        "h": 200,
        "color": "black",
        "styleKey": "gold",
        "label": 4,
        "ammo": 40
      }
    ],
    "slots": [
      {
        "x": 98,
        "y": 1130,
        "w": 194,
        "h": 126
      },
      {
        "x": 311,
        "y": 1130,
        "w": 194,
        "h": 126
      },
      {
        "x": 520,
        "y": 1130,
        "w": 194,
        "h": 126
      },
      {
        "x": 729,
        "y": 1130,
        "w": 194,
        "h": 126
      }
    ],
    "wagonSprite": {
      "x": 44,
      "y": 840,
      "w": 148,
      "h": 116,
      "anchorX": 52,
      "anchorY": 96,
      "seatOffsetX": 0,
      "seatOffsetY": -52
    },
    "wagonMask": {
      "x": 0,
      "y": 820,
      "w": 260,
      "h": 200
    },
    "boardMask": {
      "x": 0,
      "y": 0,
      "w": 1024,
      "h": 1600,
      "r": 0
    }
  },
  "queueCardCount": 7,
  "pixelArt": {
    "id": "level-11-art",
    "name": "squidward_21х21.png",
    "sourceFileName": "squidward_21х21.png",
    "artScale": 1.05,
    "offsetY": -37,
    "grid": {
      "cols": 17,
      "rows": 21
    },
    "pattern": [
      "....KKKKKKKKK....",
      "...KRRRRRRRRRK...",
      "..KRRKKKKKKKRRK..",
      ".KRRKWWWWWWWKRRK.",
      "KRRKWWWWWWWWWKRRK",
      "KRKWWWWWWWWWWWKRK",
      "KRKWWWWWWWWWWWKRK",
      "KRKWWWKWWWKWWWKRK",
      ".KRKWKEKWKEKWKRK.",
      "..KKKEEEKEEEKKK..",
      ".KKKYKEEEEEKYKKK.",
      "KRKYKKKEEEKKKYKRK",
      "KRKYEEEKEKEEEYKRK",
      "KREKYYYEKEYYYKERK",
      "KREEKKYYYYYKKEERK",
      "KKEEEEKKKKKEEEEKK",
      "KRKEEEEEEEEEEEKRK",
      "KRRKKKKKKKKKKKRRK",
      ".KRRRRRRRRRRRRRK.",
      "..KRRRRRRRRRRRK..",
      "...KKKKKKKKKKK..."
    ],
    "colorMatrix": [
      [
        null,
        null,
        null,
        null,
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        "black",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "black",
        null,
        null,
        null
      ],
      [
        null,
        null,
        "black",
        "red",
        "red",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "red",
        "red",
        "black",
        null,
        null
      ],
      [
        null,
        "black",
        "red",
        "red",
        "black",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "black",
        "red",
        "red",
        "black",
        null
      ],
      [
        "black",
        "red",
        "red",
        "black",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "black",
        "red",
        "red",
        "black"
      ],
      [
        "black",
        "red",
        "black",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "black",
        "red",
        "black"
      ],
      [
        "black",
        "red",
        "black",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "white",
        "black",
        "red",
        "black"
      ],
      [
        "black",
        "red",
        "black",
        "white",
        "white",
        "white",
        "black",
        "white",
        "white",
        "white",
        "black",
        "white",
        "white",
        "white",
        "black",
        "red",
        "black"
      ],
      [
        null,
        "black",
        "red",
        "black",
        "white",
        "black",
        "peach",
        "black",
        "white",
        "black",
        "peach",
        "black",
        "white",
        "black",
        "red",
        "black",
        null
      ],
      [
        null,
        null,
        "black",
        "black",
        "black",
        "peach",
        "peach",
        "peach",
        "black",
        "peach",
        "peach",
        "peach",
        "black",
        "black",
        "black",
        null,
        null
      ],
      [
        null,
        "black",
        "black",
        "black",
        "yellow",
        "black",
        "peach",
        "peach",
        "peach",
        "peach",
        "peach",
        "black",
        "yellow",
        "black",
        "black",
        "black",
        null
      ],
      [
        "black",
        "red",
        "black",
        "yellow",
        "black",
        "black",
        "black",
        "peach",
        "peach",
        "peach",
        "black",
        "black",
        "black",
        "yellow",
        "black",
        "red",
        "black"
      ],
      [
        "black",
        "red",
        "black",
        "yellow",
        "peach",
        "peach",
        "peach",
        "black",
        "peach",
        "black",
        "peach",
        "peach",
        "peach",
        "yellow",
        "black",
        "red",
        "black"
      ],
      [
        "black",
        "red",
        "peach",
        "black",
        "yellow",
        "yellow",
        "yellow",
        "peach",
        "black",
        "peach",
        "yellow",
        "yellow",
        "yellow",
        "black",
        "peach",
        "red",
        "black"
      ],
      [
        "black",
        "red",
        "peach",
        "peach",
        "black",
        "black",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "black",
        "black",
        "peach",
        "peach",
        "red",
        "black"
      ],
      [
        "black",
        "black",
        "peach",
        "peach",
        "peach",
        "peach",
        "black",
        "black",
        "black",
        "black",
        "black",
        "peach",
        "peach",
        "peach",
        "peach",
        "black",
        "black"
      ],
      [
        "black",
        "red",
        "black",
        "peach",
        "peach",
        "peach",
        "peach",
        "peach",
        "peach",
        "peach",
        "peach",
        "peach",
        "peach",
        "peach",
        "black",
        "red",
        "black"
      ],
      [
        "black",
        "red",
        "red",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "red",
        "red",
        "black"
      ],
      [
        null,
        "black",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "black",
        null
      ],
      [
        null,
        null,
        "black",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "red",
        "black",
        null,
        null
      ],
      [
        null,
        null,
        null,
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        null,
        null,
        null
      ]
    ],
    "birdCount": 7
  }
};
