window.PIXELFLOW_LEVEL_18 = {
  "id": "18",
  "name": "funny_monkey_meme",
  "displayName": "Monkey",
  "fallbackFieldPattern": [
    "..........KKKKKKKKK.........",
    "........KKNNNNNNNNNK........",
    "......KKNNNNNNNNNNNNKK......",
    ".....KNNNNNNNNNNNKKKNNKK....",
    "....KNNNNNNNNNNNKOOOKKNNK...",
    "...KNNNNNNNNNNNKOOOOOOKKK...",
    "...KNNNNNNNNNNKOOOOOOOOOK...",
    "..KNNNNNNNNNNNKOOOOOOOOOOK..",
    ".KNNNNNNNNNNNNKOOOOOOOOOOK..",
    ".KNNNNNNNNNNNNKOOOOKKKOOOK..",
    ".KNNNNNNNNNNNNKOOOKKKKKOKKK.",
    ".KNNNNNNNNNNNNNKOOKWWWKOKWWK",
    ".KKKKNNNNNNNNNNKOOKKWWKOKKWK",
    "KNNNNKNNNNNNNNNKOOKKWWKOKKWK",
    "KNNNNKNNNNNNNNNNKOKWWWKOKWWK",
    "KNNNOKNNNNNNNNNNKOOKKKOOKKK.",
    "KNNOOKNNNNNNNNNNKOOOOOOOOK..",
    "KNNOOOKNNNNNNNNNKOOOOOOOKKK.",
    ".KNNNNKNNNNNNNNNKOOOOOOOKKK.",
    "..KKKKKNNNNNNNNKOOOOOOOOKKK.",
    "...KNNNNNNNNNNKOOKOOOOOOOK..",
    "....KNNNNNNNNNKOOKKKKKKKKK..",
    "....KNNNNNNNNNKOOKOOOOOOOK..",
    ".....KNNNNNNNNNKOOOOOOOOOK..",
    ".....KNNNNNNNNNNKOOOOOOKK...",
    "......KKKNNNNNNNNKKKKKKKNK..",
    ".....KNNNKKNNNNNNNNNNNNNK..."
  ],
  "referenceGrid": {
    "x": 190,
    "y": 397,
    "step": 23,
    "cellSize": 21
  },
  "layout": {
    "fieldX": 190,
    "fieldY": 397,
    "fieldStep": 23,
    "cellSize": 21,
    "fieldCols": 28,
    "fieldRows": 27,
    "track": {
      "x": 106,
      "y": 189,
      "w": 808,
      "h": 856,
      "r": 50
    },
    "spawnPoint": {
      "x": 152,
      "y": 979
    },
    "cards": [
      {
        "lane": 0,
        "row": 0,
        "x": 312,
        "y": 1230,
        "w": 160,
        "h": 200,
        "color": "green",
        "styleKey": "mint",
        "label": 1,
        "ammo": 40
      },
      {
        "lane": 1,
        "row": 0,
        "x": 552,
        "y": 1230,
        "w": 160,
        "h": 200,
        "color": "black",
        "styleKey": "coral",
        "label": 2,
        "ammo": 40
      },
      {
        "lane": 0,
        "row": 1,
        "x": 312,
        "y": 1432,
        "w": 160,
        "h": 200,
        "color": "green",
        "styleKey": "sky",
        "label": 3,
        "ammo": 40
      },
      {
        "lane": 1,
        "row": 1,
        "x": 552,
        "y": 1432,
        "w": 160,
        "h": 200,
        "color": "black",
        "styleKey": "gold",
        "label": 4,
        "ammo": 40
      }
    ],
    "slots": [
      {
        "x": 98,
        "y": 1130,
        "w": 194,
        "h": 126
      },
      {
        "x": 311,
        "y": 1130,
        "w": 194,
        "h": 126
      },
      {
        "x": 520,
        "y": 1130,
        "w": 194,
        "h": 126
      },
      {
        "x": 729,
        "y": 1130,
        "w": 194,
        "h": 126
      }
    ],
    "wagonSprite": {
      "x": 44,
      "y": 840,
      "w": 148,
      "h": 116,
      "anchorX": 52,
      "anchorY": 96,
      "seatOffsetX": 0,
      "seatOffsetY": -52
    },
    "wagonMask": {
      "x": 0,
      "y": 820,
      "w": 260,
      "h": 200
    },
    "boardMask": {
      "x": 0,
      "y": 0,
      "w": 1024,
      "h": 1600,
      "r": 0
    }
  },
  "queueCardCount": 7,
  "pixelArt": {
    "id": "level-18-art",
    "name": "meme_28х28.png",
    "sourceFileName": "meme_28х28.png",
    "birdCount": 7,
    "artScale": 0.9,
    "offsetY": -37,
    "grid": {
      "cols": 28,
      "rows": 27
    },
    "pattern": [
      "..........KKKKKKKKK.........",
      "........KKNNNNNNNNNK........",
      "......KKNNNNNNNNNNNNKK......",
      ".....KNNNNNNNNNNNKKKNNKK....",
      "....KNNNNNNNNNNNKOOOKKNNK...",
      "...KNNNNNNNNNNNKOOOOOOKKK...",
      "...KNNNNNNNNNNKOOOOOOOOOK...",
      "..KNNNNNNNNNNNKOOOOOOOOOOK..",
      ".KNNNNNNNNNNNNKOOOOOOOOOOK..",
      ".KNNNNNNNNNNNNKOOOOKKKOOOK..",
      ".KNNNNNNNNNNNNKOOOKKKKKOKKK.",
      ".KNNNNNNNNNNNNNKOOKWWWKOKWWK",
      ".KKKKNNNNNNNNNNKOOKKWWKOKKWK",
      "KNNNNKNNNNNNNNNKOOKKWWKOKKWK",
      "KNNNNKNNNNNNNNNNKOKWWWKOKWWK",
      "KNNNOKNNNNNNNNNNKOOKKKOOKKK.",
      "KNNOOKNNNNNNNNNNKOOOOOOOOK..",
      "KNNOOOKNNNNNNNNNKOOOOOOOKKK.",
      ".KNNNNKNNNNNNNNNKOOOOOOOKKK.",
      "..KKKKKNNNNNNNNKOOOOOOOOKKK.",
      "...KNNNNNNNNNNKOOKOOOOOOOK..",
      "....KNNNNNNNNNKOOKKKKKKKKK..",
      "....KNNNNNNNNNKOOKOOOOOOOK..",
      ".....KNNNNNNNNNKOOOOOOOOOK..",
      ".....KNNNNNNNNNNKOOOOOOKK...",
      "......KKKNNNNNNNNKKKKKKKNK..",
      ".....KNNNKKNNNNNNNNNNNNNK..."
    ],
    "colorMatrix": [
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "black",
        "black",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "black",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        "black",
        "black",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "black",
        "black",
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        "black",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "black",
        "black",
        "black",
        "brown",
        "brown",
        "black",
        "black",
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        "black",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "black",
        "orange",
        "orange",
        "orange",
        "black",
        "black",
        "brown",
        "brown",
        "black",
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        "black",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "black",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "black",
        "black",
        "black",
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        "black",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "black",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "black",
        null,
        null,
        null
      ],
      [
        null,
        null,
        "black",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "black",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "black",
        null,
        null
      ],
      [
        null,
        "black",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "black",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "black",
        null,
        null
      ],
      [
        null,
        "black",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "black",
        "orange",
        "orange",
        "orange",
        "orange",
        "black",
        "black",
        "black",
        "orange",
        "orange",
        "orange",
        "black",
        null,
        null
      ],
      [
        null,
        "black",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "black",
        "orange",
        "orange",
        "orange",
        "black",
        "black",
        "black",
        "black",
        "black",
        "orange",
        "black",
        "black",
        "black",
        null
      ],
      [
        null,
        "black",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "black",
        "orange",
        "orange",
        "black",
        "white",
        "white",
        "white",
        "black",
        "orange",
        "black",
        "white",
        "white",
        "black"
      ],
      [
        null,
        "black",
        "black",
        "black",
        "black",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "black",
        "orange",
        "orange",
        "black",
        "black",
        "white",
        "white",
        "black",
        "orange",
        "black",
        "black",
        "white",
        "black"
      ],
      [
        "black",
        "brown",
        "brown",
        "brown",
        "brown",
        "black",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "black",
        "orange",
        "orange",
        "black",
        "black",
        "white",
        "white",
        "black",
        "orange",
        "black",
        "black",
        "white",
        "black"
      ],
      [
        "black",
        "brown",
        "brown",
        "brown",
        "brown",
        "black",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "black",
        "orange",
        "black",
        "white",
        "white",
        "white",
        "black",
        "orange",
        "black",
        "white",
        "white",
        "black"
      ],
      [
        "black",
        "brown",
        "brown",
        "brown",
        "orange",
        "black",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "black",
        "orange",
        "orange",
        "black",
        "black",
        "black",
        "orange",
        "orange",
        "black",
        "black",
        "black",
        null
      ],
      [
        "black",
        "brown",
        "brown",
        "orange",
        "orange",
        "black",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "black",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "black",
        null,
        null
      ],
      [
        "black",
        "brown",
        "brown",
        "orange",
        "orange",
        "orange",
        "black",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "black",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "black",
        "black",
        "black",
        null
      ],
      [
        null,
        "black",
        "brown",
        "brown",
        "brown",
        "brown",
        "black",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "black",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "black",
        "black",
        "black",
        null
      ],
      [
        null,
        null,
        "black",
        "black",
        "black",
        "black",
        "black",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "black",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "black",
        "black",
        "black",
        null
      ],
      [
        null,
        null,
        null,
        "black",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "black",
        "orange",
        "orange",
        "black",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "black",
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        "black",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "black",
        "orange",
        "orange",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        "black",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "black",
        "orange",
        "orange",
        "black",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "black",
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        "black",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "black",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "black",
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        "black",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "black",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "black",
        "black",
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        "black",
        "black",
        "black",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "brown",
        "black",
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        "black",
        "brown",
        "brown",
        "brown",
        "black",
        "black",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "brown",
        "black",
        null,
        null,
        null
      ]
    ]
  }
};
