window.PIXELFLOW_LEVEL_21 = {
  "id": "21",
  "name": "hamster",
  "displayName": "Hamster",
  "fallbackFieldPattern": [
    "....KKK...............KKK....",
    "...KOOOK...KKKKKKK...KOOOK...",
    "..KOOKOOKKKOOOOOOOKKKOOKOOK..",
    "..KOIEKOOOOOOOOOOOOOOOKEIOK..",
    "..KOIEKOOOOOOOOOOOOOOOKEIOK..",
    "..KOIIOOOOOOOOOOOOOOOOOIIOK..",
    "...KOOOOOOOOOOOOOOOOOOOOOK...",
    "....KKOOOKKOOOOOOOKKOOOKK....",
    ".....KOOKKWKOOOOOKWKKOOK.....",
    "....KOOOKKKKOIIIOKKKKOOOK....",
    "....KOIIOKKOIEEEIOKKOIIOK....",
    "...KOIIIIOOIIIEIIIOOIIIIOK...",
    "...KOIIIIIIKIIKIIKIIIIIIOK...",
    "...KOIIIIIIIKKIKKIIIIIIIOK...",
    "...KOIIIIIIIIIIIIIIIIIIIOK...",
    "....KOOIIIIIIKKKIIIIIIOOK....",
    ".....KKKIIIIKNNOKIIIIKKK.....",
    ".....KOOOKKKONOOWKKKOOOK.....",
    ".....KOOIIIKKNOOKKIIOOOK.....",
    "....KOOOIIEEKNOWKEEIOOOOK....",
    "....KOOOIIIIKNOWKIIIOOOOK....",
    "....KOOOOKKKIKNKIKKKOOOOK....",
    "....KOOOOOOIIOKOIOOOOOOOK....",
    "....KOOOOIIIIIIIIIIOOOOOK....",
    ".....KOOOOIIIIIIIIOOOOOK.....",
    ".....KOOKKKIIIIIIIKKKOOK.....",
    ".....KOKIIIKOIIIOKIIIKOK.....",
    "......KKEIEKOOOOOKEIEKK......",
    "........KKK.KKKKK.KKKK......."
  ],
  "referenceGrid": {
    "x": 266,
    "y": 424,
    "step": 17,
    "cellSize": 15
  },
  "layout": {
    "fieldX": 266,
    "fieldY": 424,
    "fieldStep": 17,
    "cellSize": 15,
    "fieldCols": 29,
    "fieldRows": 29,
    "track": {
      "x": 106,
      "y": 189,
      "w": 808,
      "h": 856,
      "r": 50
    },
    "spawnPoint": {
      "x": 152,
      "y": 979
    },
    "cards": [
      {
        "lane": 0,
        "row": 0,
        "x": 312,
        "y": 1230,
        "w": 160,
        "h": 200,
        "color": "green",
        "styleKey": "mint",
        "label": 1,
        "ammo": 40
      },
      {
        "lane": 1,
        "row": 0,
        "x": 552,
        "y": 1230,
        "w": 160,
        "h": 200,
        "color": "black",
        "styleKey": "coral",
        "label": 2,
        "ammo": 40
      },
      {
        "lane": 0,
        "row": 1,
        "x": 312,
        "y": 1432,
        "w": 160,
        "h": 200,
        "color": "green",
        "styleKey": "sky",
        "label": 3,
        "ammo": 40
      },
      {
        "lane": 1,
        "row": 1,
        "x": 552,
        "y": 1432,
        "w": 160,
        "h": 200,
        "color": "black",
        "styleKey": "gold",
        "label": 4,
        "ammo": 40
      }
    ],
    "slots": [
      {
        "x": 98,
        "y": 1130,
        "w": 194,
        "h": 126
      },
      {
        "x": 311,
        "y": 1130,
        "w": 194,
        "h": 126
      },
      {
        "x": 520,
        "y": 1130,
        "w": 194,
        "h": 126
      },
      {
        "x": 729,
        "y": 1130,
        "w": 194,
        "h": 126
      }
    ],
    "wagonSprite": {
      "x": 44,
      "y": 840,
      "w": 148,
      "h": 116,
      "anchorX": 52,
      "anchorY": 96,
      "seatOffsetX": 0,
      "seatOffsetY": -52
    },
    "wagonMask": {
      "x": 0,
      "y": 820,
      "w": 260,
      "h": 200
    },
    "boardMask": {
      "x": 0,
      "y": 0,
      "w": 1024,
      "h": 1600,
      "r": 0
    }
  },
  "queueCardCount": 6,
  "pixelArt": {
    "id": "level-21-art",
    "name": "hamster_31х31.png",
    "sourceFileName": "hamster_31х31.png",
    "birdCount": 6,
    "artScale": 1.1,
    "offsetY": -37,
    "grid": {
      "cols": 29,
      "rows": 29
    },
    "pattern": [
      "....KKK...............KKK....",
      "...KOOOK...KKKKKKK...KOOOK...",
      "..KOOKOOKKKOOOOOOOKKKOOKOOK..",
      "..KOIEKOOOOOOOOOOOOOOOKEIOK..",
      "..KOIEKOOOOOOOOOOOOOOOKEIOK..",
      "..KOIIOOOOOOOOOOOOOOOOOIIOK..",
      "...KOOOOOOOOOOOOOOOOOOOOOK...",
      "....KKOOOKKOOOOOOOKKOOOKK....",
      ".....KOOKKWKOOOOOKWKKOOK.....",
      "....KOOOKKKKOIIIOKKKKOOOK....",
      "....KOIIOKKOIEEEIOKKOIIOK....",
      "...KOIIIIOOIIIEIIIOOIIIIOK...",
      "...KOIIIIIIKIIKIIKIIIIIIOK...",
      "...KOIIIIIIIKKIKKIIIIIIIOK...",
      "...KOIIIIIIIIIIIIIIIIIIIOK...",
      "....KOOIIIIIIKKKIIIIIIOOK....",
      ".....KKKIIIIKNNOKIIIIKKK.....",
      ".....KOOOKKKONOOWKKKOOOK.....",
      ".....KOOIIIKKNOOKKIIOOOK.....",
      "....KOOOIIEEKNOWKEEIOOOOK....",
      "....KOOOIIIIKNOWKIIIOOOOK....",
      "....KOOOOKKKIKNKIKKKOOOOK....",
      "....KOOOOOOIIOKOIOOOOOOOK....",
      "....KOOOOIIIIIIIIIIOOOOOK....",
      ".....KOOOOIIIIIIIIOOOOOK.....",
      ".....KOOKKKIIIIIIIKKKOOK.....",
      ".....KOKIIIKOIIIOKIIIKOK.....",
      "......KKEIEKOOOOOKEIEKK......",
      "........KKK.KKKKK.KKKK......."
    ],
    "colorMatrix": [
      [
        null,
        null,
        null,
        null,
        "black",
        "black",
        "black",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "black",
        "black",
        "black",
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        "black",
        "orange",
        "orange",
        "orange",
        "black",
        null,
        null,
        null,
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        null,
        null,
        null,
        "black",
        "orange",
        "orange",
        "orange",
        "black",
        null,
        null,
        null
      ],
      [
        null,
        null,
        "black",
        "orange",
        "orange",
        "black",
        "orange",
        "orange",
        "black",
        "black",
        "black",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "black",
        "black",
        "black",
        "orange",
        "orange",
        "black",
        "orange",
        "orange",
        "black",
        null,
        null
      ],
      [
        null,
        null,
        "black",
        "orange",
        "light_beige",
        "peach",
        "black",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "black",
        "peach",
        "light_beige",
        "orange",
        "black",
        null,
        null
      ],
      [
        null,
        null,
        "black",
        "orange",
        "light_beige",
        "peach",
        "black",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "black",
        "peach",
        "light_beige",
        "orange",
        "black",
        null,
        null
      ],
      [
        null,
        null,
        "black",
        "orange",
        "light_beige",
        "light_beige",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "light_beige",
        "light_beige",
        "orange",
        "black",
        null,
        null
      ],
      [
        null,
        null,
        null,
        "black",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "black",
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        "black",
        "black",
        "orange",
        "orange",
        "orange",
        "black",
        "black",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "black",
        "black",
        "orange",
        "orange",
        "orange",
        "black",
        "black",
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        "black",
        "orange",
        "orange",
        "black",
        "black",
        "white",
        "black",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "black",
        "white",
        "black",
        "black",
        "orange",
        "orange",
        "black",
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        "black",
        "orange",
        "orange",
        "orange",
        "black",
        "black",
        "black",
        "black",
        "orange",
        "light_beige",
        "light_beige",
        "light_beige",
        "orange",
        "black",
        "black",
        "black",
        "black",
        "orange",
        "orange",
        "orange",
        "black",
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        "black",
        "orange",
        "light_beige",
        "light_beige",
        "orange",
        "black",
        "black",
        "orange",
        "light_beige",
        "peach",
        "peach",
        "peach",
        "light_beige",
        "orange",
        "black",
        "black",
        "orange",
        "light_beige",
        "light_beige",
        "orange",
        "black",
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        "black",
        "orange",
        "light_beige",
        "light_beige",
        "light_beige",
        "light_beige",
        "orange",
        "orange",
        "light_beige",
        "light_beige",
        "light_beige",
        "peach",
        "light_beige",
        "light_beige",
        "light_beige",
        "orange",
        "orange",
        "light_beige",
        "light_beige",
        "light_beige",
        "light_beige",
        "orange",
        "black",
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        "black",
        "orange",
        "light_beige",
        "light_beige",
        "light_beige",
        "light_beige",
        "light_beige",
        "light_beige",
        "black",
        "light_beige",
        "light_beige",
        "black",
        "light_beige",
        "light_beige",
        "black",
        "light_beige",
        "light_beige",
        "light_beige",
        "light_beige",
        "light_beige",
        "light_beige",
        "orange",
        "black",
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        "black",
        "orange",
        "light_beige",
        "light_beige",
        "light_beige",
        "light_beige",
        "light_beige",
        "light_beige",
        "light_beige",
        "black",
        "black",
        "light_beige",
        "black",
        "black",
        "light_beige",
        "light_beige",
        "light_beige",
        "light_beige",
        "light_beige",
        "light_beige",
        "light_beige",
        "orange",
        "black",
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        "black",
        "orange",
        "light_beige",
        "light_beige",
        "light_beige",
        "light_beige",
        "light_beige",
        "light_beige",
        "light_beige",
        "light_beige",
        "light_beige",
        "light_beige",
        "light_beige",
        "light_beige",
        "light_beige",
        "light_beige",
        "light_beige",
        "light_beige",
        "light_beige",
        "light_beige",
        "light_beige",
        "orange",
        "black",
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        "black",
        "orange",
        "orange",
        "light_beige",
        "light_beige",
        "light_beige",
        "light_beige",
        "light_beige",
        "light_beige",
        "black",
        "black",
        "black",
        "light_beige",
        "light_beige",
        "light_beige",
        "light_beige",
        "light_beige",
        "light_beige",
        "orange",
        "orange",
        "black",
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        "black",
        "black",
        "black",
        "light_beige",
        "light_beige",
        "light_beige",
        "light_beige",
        "black",
        "brown",
        "brown",
        "orange",
        "black",
        "light_beige",
        "light_beige",
        "light_beige",
        "light_beige",
        "black",
        "black",
        "black",
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        "black",
        "orange",
        "orange",
        "orange",
        "black",
        "black",
        "black",
        "orange",
        "brown",
        "orange",
        "orange",
        "white",
        "black",
        "black",
        "black",
        "orange",
        "orange",
        "orange",
        "black",
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        "black",
        "orange",
        "orange",
        "light_beige",
        "light_beige",
        "light_beige",
        "black",
        "black",
        "brown",
        "orange",
        "orange",
        "black",
        "black",
        "light_beige",
        "light_beige",
        "orange",
        "orange",
        "orange",
        "black",
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        "black",
        "orange",
        "orange",
        "orange",
        "light_beige",
        "light_beige",
        "peach",
        "peach",
        "black",
        "brown",
        "orange",
        "white",
        "black",
        "peach",
        "peach",
        "light_beige",
        "orange",
        "orange",
        "orange",
        "orange",
        "black",
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        "black",
        "orange",
        "orange",
        "orange",
        "light_beige",
        "light_beige",
        "light_beige",
        "light_beige",
        "black",
        "brown",
        "orange",
        "white",
        "black",
        "light_beige",
        "light_beige",
        "light_beige",
        "orange",
        "orange",
        "orange",
        "orange",
        "black",
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        "black",
        "orange",
        "orange",
        "orange",
        "orange",
        "black",
        "black",
        "black",
        "light_beige",
        "black",
        "brown",
        "black",
        "light_beige",
        "black",
        "black",
        "black",
        "orange",
        "orange",
        "orange",
        "orange",
        "black",
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        "black",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "light_beige",
        "light_beige",
        "orange",
        "black",
        "orange",
        "light_beige",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "black",
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        "black",
        "orange",
        "orange",
        "orange",
        "orange",
        "light_beige",
        "light_beige",
        "light_beige",
        "light_beige",
        "light_beige",
        "light_beige",
        "light_beige",
        "light_beige",
        "light_beige",
        "light_beige",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "black",
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        "black",
        "orange",
        "orange",
        "orange",
        "orange",
        "light_beige",
        "light_beige",
        "light_beige",
        "light_beige",
        "light_beige",
        "light_beige",
        "light_beige",
        "light_beige",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "black",
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        "black",
        "orange",
        "orange",
        "black",
        "black",
        "black",
        "light_beige",
        "light_beige",
        "light_beige",
        "light_beige",
        "light_beige",
        "light_beige",
        "light_beige",
        "black",
        "black",
        "black",
        "orange",
        "orange",
        "black",
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        "black",
        "orange",
        "black",
        "light_beige",
        "light_beige",
        "light_beige",
        "black",
        "orange",
        "light_beige",
        "light_beige",
        "light_beige",
        "orange",
        "black",
        "light_beige",
        "light_beige",
        "light_beige",
        "black",
        "orange",
        "black",
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        "black",
        "black",
        "peach",
        "light_beige",
        "peach",
        "black",
        "orange",
        "orange",
        "orange",
        "orange",
        "orange",
        "black",
        "peach",
        "light_beige",
        "peach",
        "black",
        "black",
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "black",
        "black",
        "black",
        null,
        "black",
        "black",
        "black",
        "black",
        "black",
        null,
        "black",
        "black",
        "black",
        "black",
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    ]
  },
  "levelNumber": 21,
  "debugOnly": false
};
