window.PIXELFLOW_LEVEL_12 = {
  "id": "12",
  "name": "gary_snail",
  "displayName": "Snail",
  "fallbackFieldPattern": [
    "....KKKKK.............",
    "..KKSSSSSKK...........",
    ".KSSSSSSSSSK..........",
    ".KSSSSCCSSSK.KKK..KKK.",
    "KSSSSSCCSSSSKYRRKKYRRK",
    "KSCCSSSSSSSSKYRKKKYRKK",
    "KSCCSKKKSSSSKYYYKKYYYK",
    "KSSSKRRRKCCSSKCK..KCK.",
    "KSSKRSSSRKCSSKCK..KCK.",
    "KSKRSSSSSRKSSKCK..KCK.",
    "KSKRSSRSSRKSSKCK..KCK.",
    "KSKRSRSRSRKSSKCK..KCK.",
    "KCKRSSSRSRKSSKCK..KCK.",
    "KCCKRSRRSRKSSKCK..KCK.",
    "KSSSKRRSSRKSK.KCKKCKK.",
    ".KSSSSSSSRKK..KCKKCK..",
    "..KSSSSSRKSSK.KCCKCK..",
    "...KSKKRKSSSSKKCCCKK..",
    "..KKKKCKCKKKCCCCCCCKK.",
    ".KCCCCCCCCCCCCCCCCCCK.",
    "..KYYYYYYYYYYYYYYYYYK.",
    "...KKKKKKKKKKKKKKKKK.."
  ],
  "referenceGrid": {
    "x": 237,
    "y": 432,
    "step": 25,
    "cellSize": 23
  },
  "layout": {
    "fieldX": 237,
    "fieldY": 432,
    "fieldStep": 25,
    "cellSize": 23,
    "fieldCols": 22,
    "fieldRows": 22,
    "track": {
      "x": 106,
      "y": 189,
      "w": 808,
      "h": 856,
      "r": 50
    },
    "spawnPoint": {
      "x": 152,
      "y": 979
    },
    "cards": [
      {
        "lane": 0,
        "row": 0,
        "x": 312,
        "y": 1230,
        "w": 160,
        "h": 200,
        "color": "green",
        "styleKey": "mint",
        "label": 1,
        "ammo": 40
      },
      {
        "lane": 1,
        "row": 0,
        "x": 552,
        "y": 1230,
        "w": 160,
        "h": 200,
        "color": "black",
        "styleKey": "coral",
        "label": 2,
        "ammo": 40
      },
      {
        "lane": 0,
        "row": 1,
        "x": 312,
        "y": 1432,
        "w": 160,
        "h": 200,
        "color": "green",
        "styleKey": "sky",
        "label": 3,
        "ammo": 40
      },
      {
        "lane": 1,
        "row": 1,
        "x": 552,
        "y": 1432,
        "w": 160,
        "h": 200,
        "color": "black",
        "styleKey": "gold",
        "label": 4,
        "ammo": 40
      }
    ],
    "slots": [
      {
        "x": 98,
        "y": 1130,
        "w": 194,
        "h": 126
      },
      {
        "x": 311,
        "y": 1130,
        "w": 194,
        "h": 126
      },
      {
        "x": 520,
        "y": 1130,
        "w": 194,
        "h": 126
      },
      {
        "x": 729,
        "y": 1130,
        "w": 194,
        "h": 126
      }
    ],
    "wagonSprite": {
      "x": 44,
      "y": 840,
      "w": 148,
      "h": 116,
      "anchorX": 52,
      "anchorY": 96,
      "seatOffsetX": 0,
      "seatOffsetY": -52
    },
    "wagonMask": {
      "x": 0,
      "y": 820,
      "w": 260,
      "h": 200
    },
    "boardMask": {
      "x": 0,
      "y": 0,
      "w": 1024,
      "h": 1600,
      "r": 0
    }
  },
  "queueCardCount": 7,
  "pixelArt": {
    "id": "level-12-art",
    "name": "gary_22х22.png",
    "sourceFileName": "gary_22х22.png",
    "artScale": 1.05,
    "offsetY": -37,
    "grid": {
      "cols": 22,
      "rows": 22
    },
    "pattern": [
      "....KKKKK.............",
      "..KKSSSSSKK...........",
      ".KSSSSSSSSSK..........",
      ".KSSSSCCSSSK.KKK..KKK.",
      "KSSSSSCCSSSSKYRRKKYRRK",
      "KSCCSSSSSSSSKYRKKKYRKK",
      "KSCCSKKKSSSSKYYYKKYYYK",
      "KSSSKRRRKCCSSKCK..KCK.",
      "KSSKRSSSRKCSSKCK..KCK.",
      "KSKRSSSSSRKSSKCK..KCK.",
      "KSKRSSRSSRKSSKCK..KCK.",
      "KSKRSRSRSRKSSKCK..KCK.",
      "KCKRSSSRSRKSSKCK..KCK.",
      "KCCKRSRRSRKSSKCK..KCK.",
      "KSSSKRRSSRKSK.KCKKCKK.",
      ".KSSSSSSSRKK..KCKKCK..",
      "..KSSSSSRKSSK.KCCKCK..",
      "...KSKKRKSSSSKKCCCKK..",
      "..KKKKCKCKKKCCCCCCCKK.",
      ".KCCCCCCCCCCCCCCCCCCK.",
      "..KYYYYYYYYYYYYYYYYYK.",
      "...KKKKKKKKKKKKKKKKK.."
    ],
    "colorMatrix": [
      [
        null,
        null,
        null,
        null,
        "black",
        "black",
        "black",
        "black",
        "black",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        null,
        "black",
        "black",
        "rose",
        "rose",
        "rose",
        "rose",
        "rose",
        "black",
        "black",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        "black",
        "rose",
        "rose",
        "rose",
        "rose",
        "rose",
        "rose",
        "rose",
        "rose",
        "rose",
        "black",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      [
        null,
        "black",
        "rose",
        "rose",
        "rose",
        "rose",
        "blue",
        "blue",
        "rose",
        "rose",
        "rose",
        "black",
        null,
        "black",
        "black",
        "black",
        null,
        null,
        "black",
        "black",
        "black",
        null
      ],
      [
        "black",
        "rose",
        "rose",
        "rose",
        "rose",
        "rose",
        "blue",
        "blue",
        "rose",
        "rose",
        "rose",
        "rose",
        "black",
        "yellow",
        "red",
        "red",
        "black",
        "black",
        "yellow",
        "red",
        "red",
        "black"
      ],
      [
        "black",
        "rose",
        "blue",
        "blue",
        "rose",
        "rose",
        "rose",
        "rose",
        "rose",
        "rose",
        "rose",
        "rose",
        "black",
        "yellow",
        "red",
        "black",
        "black",
        "black",
        "yellow",
        "red",
        "black",
        "black"
      ],
      [
        "black",
        "rose",
        "blue",
        "blue",
        "rose",
        "black",
        "black",
        "black",
        "rose",
        "rose",
        "rose",
        "rose",
        "black",
        "yellow",
        "yellow",
        "yellow",
        "black",
        "black",
        "yellow",
        "yellow",
        "yellow",
        "black"
      ],
      [
        "black",
        "rose",
        "rose",
        "rose",
        "black",
        "red",
        "red",
        "red",
        "black",
        "blue",
        "blue",
        "rose",
        "rose",
        "black",
        "blue",
        "black",
        null,
        null,
        "black",
        "blue",
        "black",
        null
      ],
      [
        "black",
        "rose",
        "rose",
        "black",
        "red",
        "rose",
        "rose",
        "rose",
        "red",
        "black",
        "blue",
        "rose",
        "rose",
        "black",
        "blue",
        "black",
        null,
        null,
        "black",
        "blue",
        "black",
        null
      ],
      [
        "black",
        "rose",
        "black",
        "red",
        "rose",
        "rose",
        "rose",
        "rose",
        "rose",
        "red",
        "black",
        "rose",
        "rose",
        "black",
        "blue",
        "black",
        null,
        null,
        "black",
        "blue",
        "black",
        null
      ],
      [
        "black",
        "rose",
        "black",
        "red",
        "rose",
        "rose",
        "red",
        "rose",
        "rose",
        "red",
        "black",
        "rose",
        "rose",
        "black",
        "blue",
        "black",
        null,
        null,
        "black",
        "blue",
        "black",
        null
      ],
      [
        "black",
        "rose",
        "black",
        "red",
        "rose",
        "red",
        "rose",
        "red",
        "rose",
        "red",
        "black",
        "rose",
        "rose",
        "black",
        "blue",
        "black",
        null,
        null,
        "black",
        "blue",
        "black",
        null
      ],
      [
        "black",
        "blue",
        "black",
        "red",
        "rose",
        "rose",
        "rose",
        "red",
        "rose",
        "red",
        "black",
        "rose",
        "rose",
        "black",
        "blue",
        "black",
        null,
        null,
        "black",
        "blue",
        "black",
        null
      ],
      [
        "black",
        "blue",
        "blue",
        "black",
        "red",
        "rose",
        "red",
        "red",
        "rose",
        "red",
        "black",
        "rose",
        "rose",
        "black",
        "blue",
        "black",
        null,
        null,
        "black",
        "blue",
        "black",
        null
      ],
      [
        "black",
        "rose",
        "rose",
        "rose",
        "black",
        "red",
        "red",
        "rose",
        "rose",
        "red",
        "black",
        "rose",
        "black",
        null,
        "black",
        "blue",
        "black",
        "black",
        "blue",
        "black",
        "black",
        null
      ],
      [
        null,
        "black",
        "rose",
        "rose",
        "rose",
        "rose",
        "rose",
        "rose",
        "rose",
        "red",
        "black",
        "black",
        null,
        null,
        "black",
        "blue",
        "black",
        "black",
        "blue",
        "black",
        null,
        null
      ],
      [
        null,
        null,
        "black",
        "rose",
        "rose",
        "rose",
        "rose",
        "rose",
        "red",
        "black",
        "rose",
        "rose",
        "black",
        null,
        "black",
        "blue",
        "blue",
        "black",
        "blue",
        "black",
        null,
        null
      ],
      [
        null,
        null,
        null,
        "black",
        "rose",
        "black",
        "black",
        "red",
        "black",
        "rose",
        "rose",
        "rose",
        "rose",
        "black",
        "black",
        "blue",
        "blue",
        "blue",
        "black",
        "black",
        null,
        null
      ],
      [
        null,
        null,
        "black",
        "black",
        "black",
        "black",
        "blue",
        "black",
        "blue",
        "black",
        "black",
        "black",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "black",
        "black",
        null
      ],
      [
        null,
        "black",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "blue",
        "black",
        null
      ],
      [
        null,
        null,
        "black",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "yellow",
        "black",
        null
      ],
      [
        null,
        null,
        null,
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        "black",
        null,
        null
      ]
    ],
    "birdCount": 7
  }
};
